- DESCRIPTION
The installation fails unless you add tidymodels/modelgenerics to Remotes since it's not yet on CRAN.
Install fails on master (on a clean machine):
```
> install_github("topepo/parsnip")
Downloading GitHub repo topepo/parsnip@master
Installing parsnip
Downloading GitHub repo tidyverse/rlang@master
Installing rlang
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save  \
--no-restore CMD INSTALL  \
'/private/var/folders/gj/cm0k4b_s42j30zs376cq_5hh0000gn/T/RtmpyhVc3D/devtools76134739508e/r-lib-rlang-8dc87a9'  \
--library='/Users/me/Library/R/3.5/library' --install-tests 
* installing *source* package ‘rlang’ ...
** libs
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I./lib/  -I/usr/local/include   -fPIC  -Wall -g -O2  -c capture.c -o …
```
> Adding tidymodels/modelgenerics to Remotes in DESCRIPTION

- docs/articles/articles/Scratch.html
- docs/articles/parsnip_Intro.html
- vignettes/articles/Scratch.Rmd
- vignettes/parsnip_Intro.Rmd
Simple PR to get warmed up. Fixing typos in the website.
> Fixing typos in website

- R/multinom_reg.R
> Only add `".pred_"` to prediction column names once

- DESCRIPTION
- NEWS.md
- R/logistic_reg.R
- R/multinom_reg.R
- tests/testthat/test_logistic_reg_glmnet.R
- tests/testthat/test_multinom_reg_glmnet.R
> Actually pull lambda from object$fit$ not object$

- DESCRIPTION
- man/C5.0_train.Rd
- man/boost_tree.Rd
- man/check_times.Rd
- man/decision_tree.Rd
- man/fit.Rd
- man/keras_mlp.Rd
- man/linear_reg.Rd
- man/logistic_reg.Rd
- man/mars.Rd
- man/mlp.Rd
- man/model_spec.Rd
- man/multi_predict.Rd
- man/multinom_reg.Rd
- man/nearest_neighbor.Rd
- man/predict.model_fit.Rd
- man/rand_forest.Rd
- man/rpart_train.Rd
- man/surv_reg.Rd
- man/svm_poly.Rd
- man/svm_rbf.Rd
- man/type_sum.model_spec.Rd
- man/xgb_train.Rd
- tests/testthat/helper-objects.R
- tests/testthat/test_linear_reg_glmnet.R
- tests/testthat/test_logistic_reg_glmnet.R
- tests/testthat/test_multinom_reg_glmnet.R
- tests/testthat/test_predict_formats.R
All tests should be run locally
> remove glmnet from suggests

- R/fit.R
- docs/dev/articles/articles/Classification.html
- docs/dev/articles/articles/Regression.html
- docs/dev/articles/articles/Scratch.html
- docs/dev/reference/fit.html
- man/fit.Rd
> better fit* S3 signature 

- R/linear_reg.R
- R/linear_reg_data.R
- R/logistic_reg.R
- R/logistic_reg_data.R
- man/linear_reg.Rd
- man/logistic_reg.Rd
- tests/testthat/helper-objects.R
- tests/testthat/test_linear_reg.R
- tests/testthat/test_logistic_reg.R
> prevent long output by stan models

- .github/workflows/R-CMD-check.yaml
- NEWS.md
- R/zzz.R
Fixes tidymodels/tidymodels.org#147
> S3 register tidy method for R 4.0

- NEWS.md
- R/engines.R
> Fix missing package error

- tests/testthat/test_boost_tree_spark.R
- tests/testthat/test_descriptors.R
- tests/testthat/test_linear_reg_spark.R
- tests/testthat/test_multinom_reg_spark.R
- tests/testthat/test_rand_forest_spark.R
This PR fixes the Spark tests that were broken when iris was removed in #333.
> Fix Spark tests

- README.Rmd
- README.md
This PR switches one more badge to https in the README.
> Use https for all badges

- .github/workflows/check-pak.yaml
- R/fit.R
- tests/testthat/test_misc.R
adds pak-based checking
closes #406
> Control classes

- R/fit.R
- man/fit.Rd
> check x column names 

- R/predict.R
- man/predict.model_fit.Rd
- man/rand_forest.Rd
Corrected a very small typo that caught my eye.
> typo (used -> uses)

- NEWS.md
the new mode and prediction types got left out of the news file in the original PR
> update NEWS based on #396

- R/survival_reg.R
- man/survival_reg.Rd
I added a mention of `update()` like in other help pages.
> streamline documentation for `survival_reg()`

- R/proportional_hazards.R
- R/survival_reg.R
- man/proportional_hazards.Rd
- man/survival_reg.Rd
Until censored is fully operational
> temporarily mark survival models as internal

- _pkgdown.yml
> add gen_additive_mod to pkgdown

- R/aaa_models.R
- man/doc-tools.Rd
- man/extract-parsnip.Rd
- man/set_new_model.Rd
The links/docs were assumed to be in parsnip.
> Doc tool update for adjacent packages

- .github/workflows/R-CMD-check.yaml
- .github/workflows/pkgdown.yaml
- .github/workflows/pr-commands.yaml
- .github/workflows/test-coverage.yaml
- R/poisson_reg.R
- R/varying.R
- _pkgdown.yml
- man/convert_helpers.Rd
- man/parsnip_update.Rd
- man/poisson_reg.Rd
- man/varying_args.Rd
to be with the other `update()` methods
> move doc for `update.poisson_reg()` 

- R/logistic_reg.R
- R/multinom_reg.R
- man/logistic_reg.Rd
- man/multinom_reg.Rd
> Add links between `logistic_reg()` and `multinom_reg()`

- man/details_pls_mixOmics.Rd
- man/rmd/pls_mixOmics.Rmd
- man/rmd/pls_mixOmics.md
> show installation code for BioC moxels

- R/tunable.R
There were some parameter ranges to tweak and a missing engine argument for brulee engines. 
Although there are already some tests in extratests, I'll add more
> Tunable update

- man/details_pls_mixOmics.Rd
- man/rmd/pls_mixOmics.Rmd
- man/rmd/pls_mixOmics.md
> use backticks rather than crossref in mixOmics docs

- R/boost_tree.R
> trim redundant whitespace before error message

- DESCRIPTION
Came across when preparing to revdepcheck!
> use new CRAN dials

- R/aaa_models.R
> remove redundant `check_mode_val` call

- R/fit_helpers.R
> remove duplicated call to `check_outcome()`

- R/linear_reg.R
- R/logistic_reg.R
- R/poisson_reg.R
- R/proportional_hazards.R
> safe-guard ridge regression with glmnet for `poisson_reg()` and `proportional_hazards()` 

- .github/workflows/R-CMD-check.yaml
Until lava package issues are resolved.
> oldrel-2 temp removed

- R/mlp.R
- man/keras_mlp.Rd
> correct documentation for `...` in `keras_mlp()`

- R/fit.R
- tests/testthat/_snaps/fit_interfaces.md
- tests/testthat/test_fit_interfaces.R
> type check `formula` input to `fit.model_spec()`

- R/misc.R
With main dev:
``` r
set.seed(1)
boots <- bootstraps(mtcars)
bench::mark(
old = 
fit_resamples(
linear_reg(),
mpg ~ .,
boots
)
)
#> 1 old           210ms    213ms      4.61    14.2MB     7.68
```
With this PR:
``` r
#> 1 new           205ms    209ms      4.79    12.8MB     7.98
```
> transition to `vec_slice()` in `spec_is_loaded()`

- R/tunable.R
> register multinomial tunable arguments for brulee

- R/fit.R
- tests/testthat/_snaps/misc.md
- tests/testthat/test_misc.R
> improve error message for `fit_xy()` when `y = NULL`

- man/details_boost_tree_lightgbm.Rd
- man/rmd/boost_tree_lightgbm.Rmd
- man/rmd/boost_tree_lightgbm.md
> remove bundle reference for lightgbm

- R/predict.R
I made a mistake in #1168 which is causing issues in https://github.com/tidymodels/extratests/actions/runs/10714353747
> add missing drop = FALSE

- R/update.R
- man/add_on_exports.Rd
> use type checkers in `update()` methods

- DESCRIPTION
- R/convert_data.R
- R/fit.R
- R/fit_helpers.R
- R/predict.R
- R/sparsevctrs.R
- tests/testthat/_snaps/sparsevctrs.md
- tests/testthat/test-sparsevctrs.R
This PR:
- use `call` argument in coerce functions
- switch to `has_sparse_elements()`
> Misc sparsevctrs
