tidymodels/parsnip

R/boost_tree.R
R/linear_reg.R
R/logistic_reg.R
R/mars.R
R/mlp.R
R/multinom_reg.R
R/nearest_neighbor.R
R/rand_forest.R
R/surv_reg.R
docs/articles/articles/Classification.html
docs/articles/articles/Scratch.html
docs/reference/boost_tree.html
docs/reference/linear_reg.html
docs/reference/logistic_reg.html
docs/reference/mars.html
docs/reference/mlp.html
docs/reference/multinom_reg.html
docs/reference/nearest_neighbor.html
docs/reference/rand_forest.html
docs/reference/surv_reg.html
man/boost_tree.Rd
man/linear_reg.Rd
man/logistic_reg.Rd
man/mars.Rd
man/mlp.Rd
man/multinom_reg.Rd
man/nearest_neighbor.Rd
man/rand_forest.Rd
man/surv_reg.Rd
vignettes/articles/Scratch.Rmd

Move dots leftward in model functions

---

R/arguments.R
R/boost_tree.R
R/linear_reg.R
R/logistic_reg.R
R/logistic_reg_data.R
R/mars.R
R/mlp.R
R/multinom_reg.R
R/nearest_neighbor.R
R/rand_forest.R
R/surv_reg.R
man/boost_tree.Rd
man/linear_reg.Rd
man/logistic_reg.Rd
man/mars.Rd
man/mlp.Rd
man/multinom_reg.Rd
man/nearest_neighbor.Rd
man/rand_forest.Rd
man/surv_reg.Rd
tests/testthat/test_args_and_modes.R

I changed the main model args + update functions + `add_args` + model-specific `translate` functions.

quosure updates

---

vignettes/articles/Classification.Rmd
vignettes/articles/Regression.Rmd

Noticed that the bake calls haven't been updates + `roc_auc` and friends have changed argument handling since last time.

update vignettes to reflect changes in argument names

---

R/varying.R
tests/testthat/test_varying.R

Fixes #131 
- The structure of `find_varying()` has been "flattened" to be easier to maintain by using a number of early exist statements.
- `find_varying()` will now _always_ return a single logical value, or fail. Previously it could return a logical vector when given a list.
- `find_varying()` now returns `FALSE` when empty elements are passed in (i.e. `length(x) == 0`). Previously it returned `logical(0)`.

Fix issue 131

---

NEWS.md
R/varying.R
tests/testthat/test_varying.R

Fixes #132 
For #132, we are still going to remove the recipe step arguments with `NULL` values. So this PR does not change anything there. However, the rest of the changes that need to be made for that issue need to happen in recipes, so let's close the parsnip issue.
This PR does add error checking for the case where a user specifies a recipes step argument as varying() when it is one of the special cased arguments that _cannot_ be varying.

Add error messaging when a step argument that cannot be varying is set to varying().

---

R/predict_numeric.R

There is no `predict_prob` function.

Fix predict_numeric error message on classification models

---

R/decision_tree.R

`type` argument passed in from `mode = "classification"` is not needed for `sparklyr::ml_decision_tree_classifier`
``` r
#> Warning: package 'parsnip' was built under R version 3.5.2
library(sparklyr)
#> Warning: package 'sparklyr' was built under R version 3.5.2
sc <- spark_connect(master = "local")
iris_tbls <- sdf_copy_to(sc, iris, overwrite = TRUE) %>%
sdf_random_split(train = 2/3, validation = 2/3, seed = 2018)
train <- iris_tbls$train
validation <- iris_tbls$validation
spark_model <- decision_tree(mode = "classification") %>%
set_engine("spark")
spark_fit <- spark_model %>%
fit(Species ~ ., data = train)
#> 1 components of `...` were not used.
#> 
#> We detected these problematic arguments:
#> * `type`
#> 
#> Did you misspecify an argument?
rlang::last_error()
#> …
```

Removed unused argument for ml_decision_tree_classifier

---

tests/testthat/helper-objects.R
tests/testthat/test_boost_tree_C50.R
tests/testthat/test_boost_tree_spark.R
tests/testthat/test_boost_tree_xgboost.R
tests/testthat/test_linear_reg.R
tests/testthat/test_linear_reg_glmnet.R
tests/testthat/test_linear_reg_keras.R
tests/testthat/test_linear_reg_spark.R
tests/testthat/test_logistic_reg.R
tests/testthat/test_logistic_reg_glmnet.R
tests/testthat/test_logistic_reg_spark.R
tests/testthat/test_logistic_reg_stan.R
tests/testthat/test_mars.R
tests/testthat/test_mlp_keras.R
tests/testthat/test_mlp_nnet.R
tests/testthat/test_multinom_reg_glmnet.R
tests/testthat/test_multinom_reg_spark.R
tests/testthat/test_nearest_neighbor_kknn.R
tests/testthat/test_rand_forest_randomForest.R
tests/testthat/test_rand_forest_ranger.R
tests/testthat/test_rand_forest_spark.R
tests/testthat/test_surv_reg_flexsurv.R
tests/testthat/test_surv_reg_survreg.R

This is a quick refactor to move control objects in tests to a single file, `helper-objects.R` as suggested in #88. This was relatively standard across tests, with exceptions for stan which needed less verbosity.
This is the easiest refactor suggested in the issue to be sure, but I'd like to handle the refactor of data references separately in smaller chunks. There's a bit of variability that will take some work to standardize, but I think it could be nice to have.

REF test_control to helper-objects

---

vignettes/articles/Scratch.Rmd

* fix typos
* lm() uses *ordinary* (not ordinal) least squares

Update Scratch.Rmd vignette

---

R/aaa_models.R
vignettes/articles/Scratch.Rmd

fixed the step numbers and a few more typos
also noticed that the pkgdown site still shows the typo from PR #233

update vignette "Making a parsnip model from scratch"

---

NEWS.md
R/predict.R
R/predict_class.R

For hard class predictions and numeric predictions, the `predict()` method was having issues when the results were already in tidymodels-tibble format.

adjust for cases where parsnip predictions are from a parsnip model

---

DESCRIPTION
R/aaa.R
R/boost_tree.R
R/decision_tree.R
R/linear_reg.R
R/logistic_reg.R
R/mars.R
R/mlp.R
R/multinom_reg.R
R/nearest_neighbor.R
R/rand_forest.R
R/surv_reg.R
R/svm_poly.R
R/svm_rbf.R
man/boost_tree.Rd
man/decision_tree.Rd
man/linear_reg.Rd
man/logistic_reg.Rd
man/mars.Rd
man/mlp.Rd
man/multinom_reg.Rd
man/nearest_neighbor.Rd
man/rand_forest.Rd
man/surv_reg.Rd
man/svm_poly.Rd
man/svm_rbf.Rd
tests/testthat/test_nearest_neighbor_kknn.R

Addresses #211. This PR implements a table in each individual model `.Rd` file to show the mapping from the parsnip parameters to the engine parameters.
Still TODO is the defaults for these parameters but that is a WHOLE THING (maybe not something that can be automated) so I plan to do that in another PR in the hopefully near future. If this piece is good as is, let's merge it.

Tables for engine specific params in model docs

---

DESCRIPTION
NEWS.md
R/svm_rbf.R
R/svm_rbf_data.R
man/rmd/svm-rbf.Rmd
man/svm_rbf.Rd

liquidSVM changes

---

vignettes/articles/Scratch.Rmd

Original URL pointed to non-existent site.

update Scratch.Rmd with correct URL

---

R/predict.R
tests/testthat/test_logistic_reg.R
tests/testthat/test_logistic_reg_glmnet.R

This PR removes names on vectors from prediction output (created by `format_num()` and similar) and updates related tests. This is related to tibble 3.0 and closes #312.
```` r
classes_wool <- logistic_reg() %>%
set_engine("glm") %>%
fit(
wool ~ .,
data = warpbreaks
)
output <- predict(classes_wool, warpbreaks, type = "prob")
output$.pred_A
#>  [1] 0.3861308 0.4313066 0.6997228 0.3751053 0.8312219 0.6797094 0.6694427
#>  [8] 0.3861308 0.8106131 0.4034408 0.4376177 0.5307937 0.3922368 0.3380998
#> [15] 0.4034408 0.5996377 0.5424232 0.6108120 0.6625599 0.4932905 0.5283378
#> [22] 0.4583089 0.3678808 0.7314750 0.5745785 0.4237337 0.5515696 0.3972744
#> [29] 0.2640826 0.4198734 0.3119537 0.4198734 0.4428135 0.5592102 0.3220797
#> [36] 0.5934557 0.6751018 0.4957547 0.4147465 …
```

Remove inner names from prediction output

---

R/decision_tree.R
R/mlp.R

I looked for other errors of this type and there were none :-)

Fix a couple of documentation typos.

---

R/predict.R
man/other_predict.Rd
man/predict.model_fit.Rd
man/svm_rbf.Rd

Add a tiny tweak to `std_error` documentation (it's on a different scale than everything else that it could get returned with) and redocument

Improve `std_error` documentation

---

R/boost_tree.R

This PR closes #310 and addresses the current [CRAN checks](https://cran.r-project.org/web/checks/check_results_parsnip.html).
I don't think we need to worry about deprecating the old objective or anything because it's been changed for so long in xgboost. This solves all the warnings showing up in tests.

Use reg:squarederror objective for xgboost

---

.github/workflows/R-CMD-check.yaml
.github/workflows/test-coverage.yaml

This PR adds testing on MacOS via GH actions back, and better aligns the R CMD check with current `usethis::use_tidy_github_actions()`.

Add MacOS testing back to parsnip

---

R/boost_tree_data.R

When converting a nameless matrix to tibble with `as_tibble()`, you need to specify `.name_repair` to avoid a warning. In this case, the colnames are set on the following line, so it makes sense to do the minimum with colnames inside the `as_tibble` call.

Avoid tibble warning.

---

R/predict.R

The last PR didn't address the `remove_intercept` logic when new samples were being passed from a workflow.

remove intercept during predict

---

R/predict.R

This updates the last PR to work well with Spark, which cannot execute:
```r
new_data[, colnames(new_data) != "(Intercept)", drop = FALSE]
```
Unit tests in [`extratests`](https://github.com/tidymodels/extratests)

Spark intercept removal

---

R/misc.R
man/add_on_exports.Rd

This reverts the change in #351 for how `update_dot_check()` takes its arg, to go back to `...` for backward compatibility.

Revert update_dot_check() to take `...`

---

.github/workflows/pkgdown.yaml
_pkgdown.yml

This PR fixes the GitHub action for pkgdown, and adds the links for the replaced articles directly to the navbar, which is somewhat nicer than having to click through multiple times.

Fix pkgdown site

---

R/fit_helpers.R
R/misc.R
tests/testthat/test_boost_tree_xgboost.R
tests/testthat/test_linear_reg.R
tests/testthat/test_mars.R
tests/testthat/test_rand_forest_ranger.R

This PR closes #80.
Before this PR, we had some good checking for the data type on outcomes for classification models. This PR extends the error checking to regression models in the fit helpers. I updated the `check_outcomes()` function and used it when appropriate (when `x` and `y` are available); as far as I can tell, this function wasn't being used before.
``` r
data(penguins, package = "modeldata")
penguins_species <- penguins$species
penguins_preds <- dplyr::select(penguins, -species)
rand_forest() %>%
set_mode("regression") %>%
set_engine("ranger") %>%
fit(species ~ ., data = penguins)
#> Error: For a regression model, the outcome should be numeric.
rand_forest() %>%
set_mode("regression") %>%
set_engine("ranger") %>%
fit_xy(x = penguins_preds, y = penguins_species) …
```

Update and make `mode` checking more robust

---

R/linear_reg_data.R
R/logistic_reg_data.R
R/multinom_reg_data.R

Closes #273.
I played around in the various `predict` functions and methods today, and I think the best place to do this reordering is in the prediction module for the two glmnet models. This is mainly because:
- the fitted object is available
- all the preprocessing has already been done
``` r
library(tidyverse)
set.seed(989)
x = matrix(rnorm(100 * length(letters)), 100, length(letters)) %>%
magrittr::set_colnames(letters)
y = rnorm(100)
glmnet_spec <- linear_reg(penalty = .1) %>%
set_engine('glmnet')
glmnet_fit <- fit_xy(glmnet_spec, x, y)
glmnet_fit %>%
predict(x)
#> # A tibble: 100 x 1
#>      .pred
#>      <dbl>
#>  1 -0.135 
#>  2  0.285 
#>  3 -0.126 
#>  4  0.222 
#>  5 -0.138 
#>  6 -0.157 
#>  7  0.0271
#>  8 -0.0215
#>  9 -0.0702
#> 10 -0.0283
#> # … with 90 …
```

Reorder columns at prediction time for glmnet

---

vignettes/articles/Models.Rmd

Just proposing that the redirect should go straight to the find/parsnip page which lists all models (saves 1 click)

Change redirect url

---

R/linear_reg_data.R
R/logistic_reg_data.R
R/multinom_reg_data.R

Closes #392 
This PR adds `drop = FALSE` for the linear, logistic, and multinomial glmnet models.
``` r
fitted_parsnip <- linear_reg(
penalty = 0.1 # set for simiplicity
) %>%
set_mode('regression') %>%
set_engine('glmnet') %>%
fit(Sepal.Length ~ Sepal.Width + Petal.Length, iris)
predict(fitted_parsnip, head(iris))
#> # A tibble: 6 x 1
#>   .pred
#>   <dbl>
#> 1  5.05
#> 2  4.95
#> 3  4.96
#> 4  5.01
#> 5  5.07
#> 6  5.24
predict(fitted_parsnip, head(iris, 1))
#> # A tibble: 1 x 1
#>   .pred
#>   <dbl>
#> 1  5.05
```
<sup>Created on 2020-11-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

Use drop = FALSE for glmnet predictions on single observation

---

R/descriptors.R

Closes #393 
The backticks in these error messages cause... errors. 🆒 😎 😭 
When this is merged in, we can look at adding back in the tests in tidymodels/extratests#12.

Remove backticks in Spark error messages

---

tests/testthat/test_boost_tree_xgboost.R

🙄  Because xgboost is failing on solaris, we received CRAN emails saying that we need to resubmit to avoid errors that occur when a required package is not available.

fix test for solaris

---

inst/rstudio/addins.dcf

The binding for the Rstudio addin wasn't updated when the function was changed from `write_parsnip_specs()` to `parsnip_addin()`. https://github.com/tidymodels/parsnip/pull/408/commits/ea6ec0dda5a78e628c83f840759cd459d3306885
This PR updates the binding

update rstudio addin binding for parsnip_addin

---

R/multinom_reg.R
man/linear_reg.Rd
man/logistic_reg.Rd
man/multinom_reg.Rd
man/rmd/linear-reg.Rmd
man/rmd/logistic-reg.Rmd

The documentation said there was a Stan engine but it's Spark:
``` r
parsnip::show_engines("multinom_reg")
#> # A tibble: 4 x 2
#>   engine mode          
#>   <chr>  <chr>         
#> 1 glmnet classification
#> 2 spark  classification
#> 3 keras  classification
#> 4 nnet   classification
```
<sup>Created on 2021-02-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Fix documentation of available engines for `multinom_reg()`

---

DESCRIPTION
NEWS.md
R/logistic_reg.R
R/logistic_reg_data.R
man/logistic_reg.Rd
man/rmd/logistic-reg.Rmd
tests/testthat/test_logistic_reg.R

This PR adds the LiblineaR engine to `logistic_reg()`.
We are currently having some real uncertainty about what is going on with the `cost` argument to `LiblineaR::LiblineaR()`. The docs say:
> cost of constraints violation (default: 1). Rules the trade-off between regularization and correct classification on data. It can be seen as the inverse of a regularization constant. 
However, for both lasso and ridge regression, treating `1 / cost` like a regularization penalty gives very different results than glmnet. It seems like LIBLINEAR is using a different optimizer or maybe solving a different thing altogether??? 😮 
Here is ridge (similar for lasso):
``` r
library(tidyverse)
data_grid <- crossing(A = seq(0.4, 4, length = 200), B = …
```

Add LiblineaR engine to `logistic_reg()`

---

NEWS.md
R/svm_linear.R
R/svm_linear_data.R
man/rmd/svm-linear.Rmd
man/svm_linear.Rd
tests/testthat/test_svm_linear.R

Closes #336 
This PR adds a second engine for `svm_linear()`. We already have `"LiblineaR"` and this PR adds `"kernlab"`.
``` r
example_split <- initial_split(two_class_dat, prop = 0.99)
example_train <- training(example_split)
example_test  <-  testing(example_split)
set.seed(123)
mod <- svm_linear() %>%
set_engine("kernlab") %>%
fit(Class ~ ., example_train)
#>  Setting default kernel parameters
mod
#> 
#> Fit time:  856ms 
#> Support Vector Machine object of class "ksvm" 
#> 
#> SV type: C-svc  (classification) 
#>  parameter : cost C = 1 
#> 
#> Linear (vanilla) kernel function. 
#> 
#> Number of Support Vectors : 358 
#> 
#> Objective Function Value : -355.0963 
#> …
```

Add kernlab engine for svm_linear()

---

NEWS.md
R/fit.R
tests/testthat/test_fit_interfaces.R

Closes #442 
Models with the new mode "censored regression" can't use `fit_xy()`, they should use `fit()`.
`surv_reg` models have also been forced to use the formula interface `fit()`. The check for that has been moved into `fit_xy()` from `check_xy_interface()` which checks the details of `x` and `y`. The corresponding tests for `check_xy_interface()` were removed. The tests for an error when using `fit_xy()` with a `surv_reg` model are untouched in `test_sruv_reg_survreg.R` and `test_surv_reg_flexsurv.R`.
The corresponding tests for models for censored regression are to be added when we have the corresponding model specs in parsnip (#444).

restrict `fit_xy()` from working for censored regression models

---

DESCRIPTION

Adding myself as a contributor as per #450 🥳 
To close #450

Add Emil as contributor

---

NEWS.md
R/logistic_reg_data.R
R/svm_linear_data.R

This PR adds sparse matrix support for the LiblineaR engine models. Closes #434.
``` r
example_split <- initial_split(two_class_dat, prop = 0.99)
example_train <- training(example_split)
example_test  <-  testing(example_split)
rec <- recipe(Class ~ ., data = example_train) %>%
step_normalize(all_numeric_predictors())
spec1 <- svm_linear() %>%
set_engine("LiblineaR") %>%
set_mode("classification")
spec2 <- logistic_reg(penalty = 0.1, mixture = 1) %>%
set_engine("LiblineaR") %>%
set_mode("classification")
sparse_bp <- hardhat::default_recipe_blueprint(composition = "dgCMatrix")
wf <- workflow() %>% …
```

Add sparse matrix support for LiblineaR engine

---

R/boost_tree.R
R/boost_tree_data.R
man/boost_tree.Rd
tests/testthat/test_boost_tree_xgboost.R

Closes #460 
The predictions previously ignored the `event_level`, they respect it now.
``` r
library(tidyverse)
library(mlbench)
library(xgboost)
#> 
#> Attaching package: 'xgboost'
#> The following object is masked from 'package:dplyr':
#> 
#>     slice
library(reprex)
data("PimaIndiansDiabetes")
df <- PimaIndiansDiabetes %>%
mutate(diabetes = fct_relevel(diabetes, 'pos'))
x <- as.matrix(df[,-ncol(df)])
y <- -as.numeric(df$diabetes)+2
xgbmat <- xgb.DMatrix(data = x, label = y)
set.seed(24)
xgb_model <- xgb.train(params = list(eta = 0.3, max_depth = 3, gamma = 0, 
colsample_bytree = 1, min_child_weight = 1, subsample = 1, 
objective = …
```

Make predictions respect `event_level` for xgboost

---

R/augment.R
tests/testthat/test-augment.R

This PR makes `augment()` return tibbles even if the input data is just a data.frame
``` r
lm_spec <- linear_reg() %>%
set_engine("lm")
lm_fit <- lm_spec %>% fit(mpg ~ ., data = mtcars)
class(mtcars)
#> [1] "data.frame"
augment(lm_fit, new_data = mtcars) %>% class()
#> [1] "tbl_df"     "tbl"        "data.frame"
```
<sup>Created on 2021-04-23 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>
To close #468

make augment() return tibbles

---

R/aaa_multi_predict.R
tests/testthat/test_misc.R

Closes #482 
This PR fixes the error message for `multi_predict()` and adds a few small tests for the error message:
``` r
data(attrition)
data_split <- initial_split(attrition, strata = "Attrition")
attrition_train <- training(data_split)
attrition_test  <- testing(data_split)
tree_mod <-
boost_tree(mode = "classification", trees = 100) %>% 
set_engine("C5.0") %>% 
fit_xy(x = attrition_train %>% dplyr::select(-Attrition), y = attrition_train$Attrition)
multi_predict(
tree_mod, 
new_data = attrition_test %>% dplyr::select(-Attrition),
trees = 80:100,
type = "prob"
)
#> # A tibble: 367 x 1
#>    .pred            
#>    <list>           
#>  1 …
```

Fix error message for `multi_predict()`

---

R/aaa_models.R
R/arguments.R
R/engines.R
tests/testthat/test_mars.R
tests/testthat/test_multinom_reg.R
tests/testthat/test_nearest_neighbor.R
tests/testthat/test_nullmodel.R
tests/testthat/test_rand_forest.R
tests/testthat/test_surv_reg.R
tests/testthat/test_svm_linear.R
tests/testthat/test_svm_liquidsvm.R
tests/testthat/test_svm_poly.R
tests/testthat/test_svm_rbf.R

Closes #426
This PR makes our handling of a _missing_ argument and a _bad_ argument a bit more consistent for `set_mode()` and `set_engine()`. There was some handling coded up in both cases but we weren't really getting those benefits for missing (or even `NULL`) inputs before. This rearranging should make help things out.
The already existing warning/replacement for engines now works:
``` r
linear_reg() %>% set_engine()
#> Warning: `engine` was NULL and updated to be `lm`
#> Linear Regression Model Specification (regression)
#> 
#> Computational engine: lm
linear_reg() %>% set_engine("ranger")
#> Error: Engine 'ranger' is not available. Please use one of: 'lm', 'glmnet', 'stan', 'spark', 'keras'
```
<sup>Created on 2021-05-11 by the [reprex …

Improve errors for `set_mode()` and `set_engine()`

---

R/aaa_models.R
R/predict_class.R
R/predict_classprob.R
R/predict_hazard.R
R/predict_interval.R
R/predict_linear_pred.R
R/predict_numeric.R
R/predict_quantile.R
R/predict_raw.R
R/predict_survival.R
R/predict_time.R
R/svm_linear_data.R
tests/testthat/test_svm_linear.R

Closes #480 
This PR adds a new little helper function `check_spec_pred_type()` to create a consistent error when a user uses an unavailable `type` at prediction time.
``` r
svm_fit <- svm_linear() %>%
set_engine("LiblineaR") %>%
fit(Class ~ ., data = two_class_dat)
glm_fit <- logistic_reg() %>%
set_engine("glm") %>%
fit(Class ~ ., data = two_class_dat)
predict(svm_fit, two_class_dat, type = "prob")
#> Error: No prob prediction method available for this model.
#> * Value for `type` should be one of: 'class', 'raw'
predict(glm_fit, two_class_dat, type = "quantile")
#> Error: No quantile prediction method available for this model.
#> * Value for `type` should be one of: 'class', 'prob', 'raw', …
```

Harmonize error for wrong prediction `type`

---

R/aaa_models.R
R/augment.R
man/augment.Rd
tests/testthat/test-augment.R

Closes #435 
This PR adds a `tryCatch()` for making the `type = "prob"` predictions in `augment()`, so that it only returns the class predictions if the class probability predictions fail:
``` r
svm_spec <- svm_linear() %>%
set_engine("LiblineaR")
svm_fit <- fit(svm_spec, Species ~ ., data = iris)
augment(svm_fit, iris)
#> # A tibble: 150 x 6
#>    Sepal.Length Sepal.Width Petal.Length Petal.Width Species .pred_class
#>           <dbl>       <dbl>        <dbl>       <dbl> <fct>   <fct>      
#>  1          5.1         3.5          1.4         0.2 setosa  setosa     
#>  2          4.9         3            1.4         0.2 setosa  setosa     
#>  3          4.7         3.2          1.3         0.2 setosa  setosa     
#>  4          4.6 …
```

`augment()` for models without class probabilities

---

DESCRIPTION
R/predict.R
R/predict_hazard.R
R/predict_survival.R
man/other_predict.Rd
man/predict.model_fit.Rd

Joint PR with https://github.com/tidymodels/censored/pull/56 (merge this parsnip one first)
This PR renames the `.time` argument of `predict()` to `time`. This is more consistent with our other arguments that get passed through the dots, like `level` and `quantile`.

Rename `predict(.time =)` to `predict(time =)`

---

NEWS.md
R/boost_tree.R
R/boost_tree_data.R
man/boost_tree.Rd
man/rmd/boost-tree.Rmd
man/xgb_train.Rd
tests/testthat/test_boost_tree_xgboost.R

closes #495
closes #461
`colsample_bytree` remains an argument to `xgb_train()`. The `mtry` parameter in `boost_tree()` parameter now points to `colsample_bynode`. 
We might want to add more engine-specific tunables to `tune` for this engine. 
@mdancho84 I think that `modeltime` would need the same switch. 
(edit for clarity)

xgboost mtry parameter swap for #495

---

NEWS.md
R/aaa_models.R
R/arguments.R
R/engines.R
tests/testthat/test_args_and_modes.R
tests/testthat/test_mars.R
tests/testthat/test_multinom_reg.R
tests/testthat/test_nearest_neighbor.R
tests/testthat/test_nullmodel.R
tests/testthat/test_rand_forest.R
tests/testthat/test_surv_reg.R
tests/testthat/test_svm_linear.R
tests/testthat/test_svm_liquidsvm.R
tests/testthat/test_svm_poly.R
tests/testthat/test_svm_rbf.R

Closes #494 
This PR harmonizes the errors (previously a mix of warnings + errors) for `set_mode()` and `set_engine()`. I made little functions for the error messages and removed the functionality to choose a default engine, as we discussed. Folks will now get results like this for the engine:
``` r
linear_reg() %>% set_engine()
#> Error: Available engines are: 'lm', 'glmnet', 'stan', 'spark', 'keras'
linear_reg() %>% set_engine(NULL)
#> Error: Available engines are: 'lm', 'glmnet', 'stan', 'spark', 'keras'
linear_reg() %>% set_engine(3)
#> Error: Available engines are: 'lm', 'glmnet', 'stan', 'spark', 'keras'
linear_reg() %>% set_engine("ranger")
#> Error: Available engines are: 'lm', 'glmnet', 'stan', 'spark', 'keras'
```
<sup>Created on 2021-05-21 by the [reprex …

Harmonize errors for `set_mode()` and `set_engine()`

---

NEWS.md
R/augment.R

Closes #506 
This PR fixes the bug in `augment()` related to how predictions were being bound on, then fed back into `predict()`. Should be all working now:
``` r
two_class_df <- two_class_dat %>% mutate(id = row_number())
rec <- recipe(Class ~ ., data = two_class_df) %>%
update_role(id, new_role = "id")
tree_spec <- boost_tree() %>%
set_engine("xgboost") 
tree_fit <- workflow() %>%
add_model(tree_spec) %>%
add_recipe(rec) %>%
fit(data = two_class_df)
#> [10:21:15] WARNING: amalgamation/../src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with …
```

Fix `augment` bug 🐛 related to `bind_cols()`

---

R/aaa_multi_predict.R
man/has_multi_predict.Rd
man/multi_predict.Rd

fixed function name in docs + some formatting

docs for `multi_predict()` tools

---

DESCRIPTION

The previous PR added a bunch of examples and fails with
```
-- RMarkdown error -------------------------------------------------------------
Quitting from lines 300-303 (Examples.Rmd) 
Error : This engine requires some package installs: 'glmnet'
```
because we didn't tell pkgdown to install the required modeling packages.

add packages for Examples.Rmd

---

NEWS.md
R/aaa_models.R
R/arguments.R
R/engines.R
R/misc.R
R/translate.R
man/details_gen_additive_mod_mgcv.Rd
man/extract-parsnip.Rd
man/rmd/boost_tree_C5.0.Rmd
man/rmd/decision_tree_C5.0.Rmd
tests/testthat/test_args_and_modes.R

closes #529 
``` r
data(mtcars)
dt_reg_spec <- decision_tree() %>% 
set_mode("regression") %>% 
set_engine("C5.0")
#> Error: Available modes for engine C5.0 are: 'unknown', 'classification'
dt_reg_spec <- decision_tree() %>% 
set_engine("C5.0") %>% 
set_mode("regression")
#> Error: Available modes for engine C5.0 are: 'unknown', 'classification'
```
<sup>Created on 2021-07-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

better engine and mode checking code

---

NEWS.md
_pkgdown.yml

as mentioned in #527, the dev mode for pkgdown should go back to `auto` - and I've added the missing bullet in the NEWS file

cleanup after examples article

---

NEWS.md
R/logistic_reg_data.R

Closes #551 
The `penalty` (`cost`) for the LiblineaR engine of `logistic_reg()` does not allow for the [submodel "trick"](https://tune.tidymodels.org/articles/extras/optimizations.html#sub-model-speed-ups-1).
``` r
data(lending_club)
folds <- vfold_cv(lending_club, v = 5)
spec <- logistic_reg(penalty = tune()) %>% 
set_engine("LiblineaR") %>% 
set_mode("classification")
tune_grid(
spec,
Class ~ int_rate,
resamples = folds,
grid = 3
)
#> # Tuning results
#> # 5-fold cross-validation 
#> # A tibble: 5 × 4
#>   splits              id    .metrics         .notes          
#>   <list>              <chr> <list>           <list>          
#> 1 <split …
```

LiblineaR penalty does *not* allow submodel "trick"

---

R/model_object_docs.R
man/model_spec.Rd

Closes #554 
This PR fixes the formatting on the bulleted list for `model_spec()`

Fix bulleted list for `model_spec()`

---

vignettes/articles/Examples.Rmd
vignettes/articles/template-cls-multi-class.R
vignettes/articles/template-cls-two-class.R
vignettes/articles/template-reg-chicago.R

The article now has engine-specific section headings to reduce direct repetition in the table of contents. So now you get 
instead of

Fix TOC of Examples article

---

DESCRIPTION
NEWS.md
R/predict.R
man/bart-internal.Rd
man/predict.model_fit.Rd

_All_ prediction types with list columns should name the list column `.pred`. 
For tidymodels/censored#100

use .pred instead of .pred_survival at highest level

---

R/convert_data.R
R/fit_helpers.R
tests/testthat/test_convert_data.R

Follow up to #569 
This PR removes the ability to specify `offset` through the `...` of the converter functions. Instead, you have to supply it inline in the formula.
That said, while the `.convert_*()` functions seem to be working right, I think that offsets are pretty broken in parsnip right now. If you supply an `+ offset(col)` in the formula of `fit()`, I don't think it ever gets to the model call. Similarly, I don't think the offset is ever used at prediction time. Fixing that is out of scope for this PR, but I added a few TODOs in places where I think this issue is relevant.

Remove ability to pass `offset` through `...`

---

DESCRIPTION
vignettes/articles/Examples.Rmd
vignettes/articles/template-cls-two-class.R

add examples for `bart()` and `gen_additive_mod()` which have engines in parsnip

Update Examples article

---

.github/workflows/R-CMD-check.yaml
DESCRIPTION
NEWS.md
R/convert_data.R
tests/testthat/test_convert_data.R

`maybe_matrix()` not checks and gives an informative error when non-numeric columns are present.

check for non-numeric cols when converting to matrix

---

DESCRIPTION
R/aaa_models.R
R/bag_tree.R
R/boost_tree_data.R
R/decision_tree_data.R
man/set_new_model.Rd

closes #603
Sets the mode "censored regression" for bag_tree, boost_tree, and decision_tree here instead of in censored.

Set mode "censored regression"

---

DESCRIPTION
R/tunable.R
R/zzz.R

This PR is part of moving methods for `tunable()` from tune to the package which holds the corresponding object class:
* the methods for `recipe`, `step`, and `check` are already in recipes, that PR just cleans up the documentation. https://github.com/tidymodels/recipes/pull/856
* the methods for `model_spec` and various model types such as `linear_reg` etc are moved to parsnip (aka this PR here)
* the method for `workflow` is moved to workflows https://github.com/tidymodels/workflows/pull/130
When methods have been moved, the methods are registered conditionally on the version of tune from which they have been removed. The tune PR is https://github.com/tidymodels/tune/pull/433
The tests require multiple packages so they are all in extratests: …

move methods for `tunable()` from tune to parsnip

---

NEWS.md
R/aaa.R
R/control_parsnip.R
R/fit.R
R/fit_helpers.R
man/control_parsnip.Rd
man/details_gen_additive_mod_mgcv.Rd
tests/testthat/test_fit_interfaces.R

Updates to execution time collection

---

NEWS.md
R/bart.R
R/predict.R
R/predict_quantile.R
R/predict_survival.R
man/bart-internal.Rd
man/other_predict.Rd
man/predict.model_fit.Rd

This is prep for https://github.com/tidymodels/censored/pull/125 and introduces the `interval` argument for predictions which allows to add confidence or prediction interval estimats to be added, if available.  
It makes use of the new arg for predictions of type `"survival"` and `"quantile"`, thus covering part of #616.

add argument `interval` for survival/quantile predictions

---

NEWS.md
R/fit_helpers.R
tests/testthat/test_linear_reg.R

Closes #621 
This PR updates `form_form()` and `form_xy()` so that all four fit paths use the same `check_outcome()` helper function.
``` r
parsnip::fit(
parsnip::decision_tree(mode = "regression"),
status ~ wind,
data = dplyr::storms)
#> Error in `check_outcome()` at parsnip/R/fit_helpers.R:9:4:
#> For a regression model, the outcome should be numeric.
```
<sup>Created on 2021-12-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Use `check_outcome` for all fit paths

---

.github/workflows/R-CMD-check.yaml

We think the `v2` actions will solve a lot of the package dependency problems that still crop up.

Move up to `v2` actions

---

DESCRIPTION
NEWS.md
R/aaa_models.R
R/boost_tree_data.R
R/decision_tree_data.R
R/gen_additive_mod_data.R
R/mlp_data.R
R/proportional_hazards_data.R
R/rand_forest_data.R
R/survival_reg_data.R
man/set_new_model.Rd
tests/testthat/test_args_and_modes.R
tests/testthat/test_registration.R

Closes #604 
Non-breaking change; fixes issue with vetiver getting package dependencies across _all model modes_. 
Some changes will be made to parsnip extension packages at our leisure (but most importantly to censored).

Mode specific dependencies

---

.github/workflows/test-coverage.yaml

Update test-coverage GHA

---

NEWS.md
R/multinom_reg.R
tests/testthat/test_multinom_reg_nnet.R

This PR aims to close https://github.com/tidymodels/parsnip/issues/612
`organize_nnet_prob()` is only used in [one place](https://github.com/tidymodels/parsnip/search?q=organize_nnet_prob) so it is small scope fix.

Allow multinom_reg() using nnet engine to work with 1 row prob predictions

---

.github/workflows/R-CMD-check.yaml

Some minor updates to the GHA tensorflow setup:
- Skip manually creating r-reticulate conda env (it's auto created by `install_miniconda()`
- Remove workaround for reticulate not finding miniconda on macOS (fixed in reticulate already).
- Bump TF version to latest patch release of TF v1 (1.15.5 today)
- Specify required Python version in `install_tensorflow()` call.
- Bump Python version to 3.7, latest supported by TF 1

Update tensorflow setup

---

.github/workflows/pkgdown.yaml
.github/workflows/test-coverage.yaml
DESCRIPTION
NEWS.md
R/boost_tree.R
tests/testthat/test_boost_tree_xgboost.R

This is a fix for issue #655 
As `ntreelimit` as been deprecated, adding `iterationrange` to the
`xgb_pred` call with the correct modifications to fit the current use case.
Further work is needed at a later stage to extend the new functionality of `iterationrange`.

`ntreelimit` has been `deprecated` in favour of iteration_range

---

R/aaa.R

Closes #645 
This will add a bullet [when we do `usethis::use_release_issue()`](https://usethis.r-lib.org/reference/use_release_issue.html).

Add release bullet about `knit_engine_docs()`

---

NEWS.md
R/aaa_models.R
tests/testthat/test_re_registration.R
tests/testthat/test_registration.R

Closes #653 
Models components (e.g. fit, pred, etc) can now be re-registered as long as the information is the same. 
One caveat:  package dependencies cannot be check for the same values since those are set one value at a time.

Re-registration of model information

---

R/fit_helpers.R

To close https://github.com/tidymodels/parsnip/issues/671
``` r
library(sparklyr)
#> 
#> Attaching package: 'sparklyr'
#> The following object is masked from 'package:stats':
#> 
#>     filter
sc <- spark_connect("local")
iris_tbl <- sdf_copy_to(sc, iris)
decision_tree(engine = "spark") %>%
fit(Species ~ Sepal_Length + Petal_Length, iris_tbl)
#> 
#> Formula: Species ~ Sepal_Length + Petal_Length
#> 
#> DecisionTreeClassificationModel (uid=decision_tree_classifier__6a7e32a5_0707_461f_bfe5_d825c6b6f9f1) of depth 5 with 17 nodes
spark_disconnect(sc)
```
<sup>Created on 2022-03-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
Should I add a corresponding test in …

don't use check_outcome() when using sparklyr

---

NEWS.md

`extract_parameter*()` methods are not bug-fixes

touch-up on NEWS for `0.2.0`

---

R/engines.R
man/set_engine.Rd

I was confused with how to pass arguments directly to the fit function (see https://github.com/tidymodels/discrim/pull/48) so this refines the language of the `set_engine` documentation so that hopefully others might avoid the same confusion.

refine documentation of set_engine to make passing arguments to the engine fit function clearer

---

R/aaa_models.R
R/descriptors.R
R/engine_docs.R
R/fit.R
R/misc.R
tests/testthat/test_misc.R

remove unused functions

---

NEWS.md
R/gen_additive_mod_data.R
tests/testthat/test_gen_additive_model.R

This pull request contains a minor code change that addresses an inconsistency for probability predictions for two class GAM models -- see issue #708.

Fixing inconsistency for probability predictions for two class GAM models 

---

R/partykit.R

it didn't return the results of the evaluation in the environment _with_ the weights which caused the cforests tests in censored to fail. Possibly also the reason for https://github.com/tidymodels/bonsai/issues/9

fix `cforest_train()`

---

R/linear_reg.R
R/logistic_reg.R
R/multinom_reg.R
R/poisson_reg.R
man/linear_reg.Rd
man/logistic_reg.Rd
man/multinom_reg.Rd
man/parsnip_update.Rd
man/poisson_reg.Rd
man/proportional_hazards.Rd
man/rmd/linear_reg_spark.Rmd
man/rmd/linear_reg_spark.md
man/rmd/logistic_reg_glmnet.Rmd
man/rmd/logistic_reg_glmnet.md
man/rmd/logistic_reg_spark.Rmd
man/rmd/logistic_reg_spark.md
man/rmd/multinom_reg_glmnet.Rmd
man/rmd/multinom_reg_glmnet.md
man/rmd/multinom_reg_spark.Rmd
man/rmd/multinom_reg_spark.md
man/rmd/poisson_reg_glmnet.Rmd
man/rmd/poisson_reg_glmnet.md
man/rmd/proportional_hazards_glmnet.Rmd
man/rmd/proportional_hazards_glmnet.md

Closes #570. In my experience, "interpolate" is the verbiage here. :)
Will need someone else to generate documentation for me—spent a while trying to debug, and eventually came across a set of errors in `knit_engine_docs`:
```
Failed with error:  'package 'parsnip' required by 'censored' could not be found'
Failed with error:  'package 'parsnip' required by 'discrim' could not be found'
```
that's not worth me troubleshooting if others are able to follow [inst/README-DOCS.md](https://github.com/tidymodels/parsnip/blob/main/inst/README-DOCS.md) just fine.🛫

document elastic net regularization via mixture

---

man/details_naive_Bayes_naivebayes.Rd
man/rmd/naive_Bayes_klaR.Rmd
man/rmd/naive_Bayes_klaR.md
man/rmd/naive_Bayes_naivebayes.Rmd
man/rmd/naive_Bayes_naivebayes.md

Missing documentation has been added to close https://github.com/tidymodels/parsnip/issues/712.

add missing comment about usekernel in naive_Bayes naivebayes

---

NEWS.md
R/predict_classprob.R
tests/testthat/test_predict_formats.R

Closes #720.
One thing I'd appreciate an eye for from folks who have a better sense for `model_spec` objects than I do: do `spec$lvl` and `spec$preproc$y_var` always exist for relevant cases here? Do we need to unit test this more thoroughly with other model specs?
``` r
library(tibble)
x <- tibble(
boop = factor(sample(c("class", "class_1"), 100, replace = TRUE)),
bop = rnorm(100),
beep = rnorm(100)
)
mod <- logistic_reg() %>%
set_mode(mode = "classification") %>%
fit(boop ~ bop + beep, data = x)
predict(mod, type = "prob", new_data = x)
#> Error:
#> ! The outcome variable `boop` has a level called 'class'. This level is reserved for parsnip's classification internals; please adjust the levels to use a different value.
```
<sup>Created on 2022-05-11 by the [reprex …

error on `predict(type = "prob")` with outcome level named `"class"`

---

tests/testthat/test_registration.R

The function `test_by_col()` was added in https://github.com/tidymodels/parsnip/commit/4b0808f9f5270f06a6d5e8e7d5162dd843ef9852 a little over 3 years ago. It should be fine to use `expect_equal()` instead.

remove test_by_col function and its use

---

R/aaa_models.R

there are a couple of places where `get_model_env()` is being called without having its results being used. Some of these changes date back to https://github.com/tidymodels/parsnip/commit/218cc73064d20e44bc0358124eced6c0b067ecd4

remove unused calls to get_model_env()

---

DESCRIPTION
R/rule_fit.R
man/rmd/boost_tree_xgboost.Rmd
man/rmd/boost_tree_xgboost.md
man/rmd/rule_fit_xrf.Rmd
man/rmd/rule_fit_xrf.md
man/rmd/template-early-stopping.Rmd
man/rule_fit.Rd

Will be followed up by a larger PR to rules in a moment. :)

add `stop_iter` as a main argument to `rule_fit()`

---

NEWS.md
R/nullmodel_data.R
tests/testthat/_snaps/nullmodel.md
tests/testthat/test_nullmodel.R

Closes #752
There was no `pkg` slot in the `set_fit()` call which errored `print.model_spec()`.

missing pkg specification for #752

---

.github/workflows/R-CMD-check.yaml
.github/workflows/old-tensorflow.yaml

Attempting to address GHA failures. 
At the moment, looking like pak "install planning" failures. Looks like there's been a release of reticulate since we started using the dev version, so trying to install the CRAN version first.

address GHA failures

---

R/linear_reg.R
R/logistic_reg.R

Related to, but doesn't fully fix, tidymodels/tune#526.
``` r
workflow(
preprocessor = mpg ~ .,
spec = linear_reg(engine = 'glmnet', penalty = tune(), mixture = 1)
) %>% 
tune_grid(resamples = vfold_cv(mtcars))
#> # Tuning results
#> # 10-fold cross-validation 
#> # A tibble: 10 × 4
#>    splits         id     .metrics          .notes          
#>    <list>         <chr>  <list>            <list>          
#>  1 <split [28/4]> Fold01 <tibble [20 × 5]> <tibble [0 × 3]>
#>  2 <split [28/4]> Fold02 <tibble [20 × 5]> <tibble [0 × 3]>
#>  3 <split [29/3]> Fold03 <tibble [20 × 5]> <tibble [0 × 3]>
#>  4 <split [29/3]> Fold04 <tibble [20 × 5]> <tibble [0 × 3]>
#>  5 <split [29/3]> Fold05 <tibble [20 × 5]> <tibble [0 × 3]>
#>  6 <split [29/3]> Fold06 <tibble [20 × 5]> <tibble …
```

address dev dplyr join warnings

---

man/details_auto_ml_h2o.Rd
man/details_boost_tree_h2o.Rd
man/details_linear_reg_gls.Rd
man/details_linear_reg_h2o.Rd
man/details_logistic_reg_h2o.Rd
man/details_mlp_h2o.Rd
man/details_multinom_reg_h2o.Rd
man/details_naive_Bayes_h2o.Rd
man/details_poisson_reg_h2o.Rd
man/details_proportional_hazards_glmnet.Rd
man/details_rand_forest_h2o.Rd
man/details_rule_fit_h2o.Rd
man/glmnet-details.Rd
man/rmd/boost_tree_h2o.md
man/rmd/glmnet-details.md
man/rmd/linear_reg_gls.md
man/rmd/linear_reg_h2o.md
man/rmd/logistic_reg_h2o.md
man/rmd/mlp_h2o.md
man/rmd/multinom_reg_h2o.md
man/rmd/naive_Bayes_h2o.md
man/rmd/poisson_reg_h2o.md
man/rmd/proportional_hazards_glmnet.md
man/rmd/rand_forest_h2o.md
man/rmd/rule_fit_h2o.md

Output of:
```
parsnip::install_engine_packages()
parsnip::knit_engine_docs()
devtools::document()
```

regenerate engine docs

---

R/bart.R

Fix dbarts class prediction order 

---

tests/testthat/_snaps/translate.md
tests/testthat/test_translate.R

This tests the error message for trying to use `proportional_hazards()` with the `glmnet` engine _without_ a penalty value because that's the thing the `translate()` method for PH models does in addition to the default translate() method.
The rest of the tests for `proportional_hazards()` and `survival_reg()` is more of a placeholder because parsnip does not have any engines for these models. The actual tests on primary and engine args for those models are in censored, see https://github.com/tidymodels/censored/pull/208.

Tests for survival models

---

R/tunable.R
man/details_boost_tree_lightgbm.Rd
man/rmd/boost_tree_lightgbm.Rmd
man/rmd/boost_tree_lightgbm.md

Some adjustments to effectively enable + document the `sample_size` argument for the lightgbm engine. Will be followed up by a PR in bonsai—1/2 to close tidymodels/bonsai#30.
The gist:
https://github.com/tidymodels/parsnip/blob/713d617274b54a9f99c5b67c2cf52a7b0a3e431c/man/rmd/boost_tree_lightgbm.Rmd#L79-L81
Will PR as draft and we can come back to this after conf. :)

docs and `tunable_boost_tree` adjustments re: lightgbm bagging

---

tests/testthat/_snaps/translate.md

Looks like this won't print in non-interactive sessions post-pillar 1.8.1!

update snaps to remove tibble print suggestion

---

NEWS.md
R/fit.R
R/fit_helpers.R
R/translate.R
parsnip.Rproj
tests/testthat/test_fit_interfaces.R

Make fit_xy() fail when mode is unknown

---

R/arguments.R
R/engines.R
R/extract.R
R/fit.R
R/misc.R
R/print.R
man/add_on_exports.Rd
tests/testthat/_snaps/extract.md
tests/testthat/test_extract.R

Introduces the missing implementation prompt as an error on `extract_parameter*dials`. Only needs added to `extract_parameter_set_dials`, which is called by `extract_parameter_dials`. We only add this to the `.model_spec` methods, as the prompt is raised already for workflows via https://github.com/tidymodels/workflows/pull/175 by then. :)
``` r
bt_mod <- bag_tree(min_n = tune()) %>%
set_mode("regression")
extract_parameter_set_dials(bt_mod)
#> Error:
#> ! parsnip could not locate an implementation for `bag_tree` regression
#>   model specifications.
#> ℹ The parsnip extension package baguette implements support for this
#>   specification.
#> ℹ Please install (if needed) and load to continue.
extract_parameter_dials(bt_mod, parameter = "min_n")
#> Error:
#> ! parsnip …
```

prompt on parameter extraction when implementation is missing

---

R/aaa_models.R
R/arguments.R
R/engines.R
R/misc.R
R/translate.R
tests/testthat/_snaps/args_and_modes.md
tests/testthat/test_args_and_modes.R

The names of internal functions are shown in the message for a few different user-facing model registration errors. This PR proposes updating the call information in a few of those errors to reduce cognitive load + improve readability.
On CRAN:
``` r
linear_reg() %>%
set_engine("boop") %>%
set_mode("regression")
#> Error in `check_spec_mode_engine_val()`:
#> ! Engine 'boop' is not supported for `linear_reg()`. See `show_engines('linear_reg')`.
linear_reg(engine = "boop") %>%
set_mode("regression")
#> Error in `check_spec_mode_engine_val()`:
#> ! Engine 'boop' is not supported for `linear_reg()`. See `show_engines('linear_reg')`.
```
<sup>Created on 2022-09-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
With this PR:
``` r …
```

set `call` in internal model registration errors

---

R/print.R
tests/testthat/_snaps/boost_tree.md
tests/testthat/_snaps/decision_tree.md
tests/testthat/_snaps/mars.md
tests/testthat/_snaps/misc.md
tests/testthat/_snaps/model_basics.md
tests/testthat/_snaps/nearest_neighbor.md
tests/testthat/_snaps/print.md

The model spec printing method calls out the spec’s mode:
``` r
boost_tree(mode = "regression")
#> Boosted Tree Model Specification (regression)
#> 
#> Computational engine: xgboost
```
When the `mode` is `"unknown"`, the output `(unknown)` beside the model spec’s type is ambiguous.
``` r
boost_tree()
#> Boosted Tree Model Specification (unknown)
#> 
#> Computational engine: xgboost
```
This PR proposes printing `(unknown mode)` instead:
``` r
boost_tree()
#> Boosted Tree Model Specification (unknown mode)
#> 
#> Computational engine: xgboost
```
<sup>Created on 2022-09-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

print `(unknown mode)` instead of `(unknown)`

---

DESCRIPTION
NEWS.md
R/fit.R
R/misc.R
tests/testthat/test_proportional_hazards.R
tests/testthat/test_survival_reg.R

This PR enables the matrix interface via `fit_xy()` for the `"censored regression"` mode.
Tests for this are in censored: https://github.com/tidymodels/censored/pull/225

Enable `fit_xy()` for censored regression

---

R/misc.R

😮
With CRAN parsnip:
``` r
set.seed(1)
dat <- tibble(x = rnorm(1e7), y = x + rnorm(1e7, sd = .2))
system.time({
linear_reg() %>%
fit(y ~ x, dat)
})
#>    user  system elapsed 
#>   4.108   0.158   4.267
```
<sup>Created on 2022-10-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
With this PR:
``` r
set.seed(1)
dat <- tibble(x = rnorm(1e7), y = x + rnorm(1e7, sd = .2))
system.time({
linear_reg() %>%
fit(y ~ x, dat)
})
#>    user  system elapsed 
#>   1.251   0.187   1.442
```
<sup>Created on 2022-10-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
Closes #834.
`check_outcome` is a bit conditional-heavy, though I have trouble imagining how these could be converted to switch- or tibbled-based logic elegantly.

check outcome class conditional on whether `y` is atomic

---

DESCRIPTION
NEWS.md
R/tunable.R

This PR makes use of https://github.com/tidymodels/dials/pull/256 to make the `num_leaves` engine arg of lightgbm tunable. 
Having the news bullet here instead of bonsai feels a little off but I guess it's the best place?

make lightgbm's `num_leaves` engine arg tunable

---

vignettes/articles/Submodels.Rmd

I think there was some mix-up with this sentence.

Typos: cheap -> cheaply; and can -> which

---

R/predict.R

`prepare_data()` is called within the `predict_<prediction type>().model_fit()` methods, on the `model_fit` and the `new_data`. If we converted the training data between different interfaces (matrix vs formula), we also convert the `new_data` at prediction time, via `.convert_form_to_xy_new()` and `.convert_xy_to_form_new()` respectively. Whether those get called is determined based on the objects in the `$preproc` of the fitted parsnip model.
I've refactored this here to use variable names for the conditions, to make it easier to understand which preproc items are linked to which conversion.
The main question for review is: is it okay to rely _only_ on the names of the preproc items? The previous version relied on them to decide _if_ any `.convert_*()` function should be applied. The …

Refactor `prepare_data()` 

---

tests/testthat/_snaps/poisson_reg.md
tests/testthat/test-poisson_reg.R

We generally try to put tests on the basic model function (like `poisson_reg()`) in parsnip since the model definitions now live here. This PR moves some of those tests from poissonreg to here.
The corresponding PR to remove them from poissonreg is: https://github.com/tidymodels/poissonreg/pull/55

Tests for `poisson_reg()`

---

R/poisson_reg.R

closes  #757
I'll add the corresponding test to the other glmnet tests for `poisson_reg()` in extratests.
``` r
library(poissonreg)
#> Loading required package: parsnip
poisson_reg(penalty = c(0.01, 0.1)) %>% 
set_engine("glmnet") %>% 
fit(count ~ (.)^2, data = seniors)
#> Error in `.check_glmnet_penalty_fit()` at parsnip/R/poisson_reg.R:89:4:
#> ! For the glmnet engine, `penalty` must be a single number (or a value of `tune()`).
#> • There are 2 values for `penalty`.
#> • To try multiple values for total regularization, use the tune package.
#> • To predict multiple penalties, use `multi_predict()`
poisson_reg() %>% 
set_engine("glmnet") %>% 
fit(count ~ (.)^2, data = seniors)
#> Error in `.check_glmnet_penalty_fit()` at parsnip/R/poisson_reg.R:89:4:
#> ! For the glmnet engine, `penalty` …
```

glmnet: Require users to set `penalty` value for `poisson_reg()`

---

DESCRIPTION
R/logistic_reg.R
R/multinom_reg.R

closes #858 
This PR moves where we set `s`, glmnet's argument for the penalty value, from inside the relevant `multi_predict()` method into the relevant `predict_raw()` method. 
This means that now the default penalty value specified in the parsnip spec will be used when `penalty = NULL`, also for for `type = "raw"` (aka the original issue).
This also means that the call stack for `multi_predict()` for logistic and multinomial regression now follows that of linear regression and what happens in the code is what was laid out in the comments, e.g.,
https://github.com/tidymodels/parsnip/blob/2249cbb6fb2c3b2038ed8c660ff67bf2f9e06be7/R/logistic_reg.R#L209-L234
The tests are in extratests: https://github.com/tidymodels/extratests/pull/72
``` r
data(lending_club, package = …
```

Setting the penalty for logistic and multinomial regression with glmnet

---

DESCRIPTION
R/multinom_reg.R

Closes #859 
The corresponding test in extratest is update here:
This PR is to be merged before the one on extratests.
``` r
data("hpc_data", package = "modeldata", envir = rlang::current_env())
mr_spec <- multinom_reg(penalty = 0.1) %>% set_engine("glmnet")
f_fit <- fit(mr_spec, class ~ protocol + log(compounds) + input_fields,
data = hpc_data)
f_pred_class <- multi_predict(f_fit, hpc_data, penalty = c(0.01, 0.1), 
type = "class")
f_pred_class$.pred[[1]]
#> # A tibble: 2 × 2
#>   penalty .pred_class
#>     <dbl> <fct>      
#> 1    0.01 VF         
#> 2    0.1  VF
f_pred_prob <- multi_predict(f_fit, hpc_data, penalty = c(0.01, 0.1), 
type = "prob")
f_pred_prob$.pred[[1]]
#> # A tibble: 2 × 5
#>   penalty .pred_VF .pred_F .pred_M .pred_L
#>     <dbl>    <dbl>   <dbl> …
```

Switch column order of `multi_predict()` result for `multinom_reg(engine = "glmnet")`

---

R/linear_reg.R
R/logistic_reg.R
R/multinom_reg.R

This PR puts the formatting code from various `multi_predict()` methods for glmnet models into their own functions. The goal is to make it easier to see the similarities between those `multi_predict()` methods and down the line make them one, calling the different formatting functions.
The glmnet tests in extratests run fine locally and will kick in on GHA once this PR is merged into the dev version of parsnip.

encapsulate glmnet formatting code

---

R/predict.R
man/bart-internal.Rd
man/other_predict.Rd
man/predict.model_fit.Rd

A lot of what `predict.model_fit()` takes as arguments and what it returns depends on the type of prediction. To make this relatively long and detailed page easier to skim, I've replaced various different descriptions of the prediction type, with mentions of `type = "<whatever the type>"`.

Improve readability of docs for `predict.model_fit()`

---

R/glmnet.R
R/linear_reg.R
R/logistic_reg.R
R/multinom_reg.R

This PR consolidates the different flavors of predict methods (`predict()`, `predict_<type>()` and `multi_predict()`) for different glmnet model types into one function per predict method flavor. 
The goal is to bring it all in one place to more easily maintain/apply changes. I'm currently not touching the class of the glmnet `model_fit` objects (yet?).
The glmnet tests in extratests run fine locally with this change. They'll run on CI when this in `main`.

Consolidate glmnet predict methods

---

R/aaa_models.R
R/glmnet.R

closes  #877 
`predict_glmnet()` calls `predict.model_fit()` which checks this via `check_pred_type_dots()` so we don't need it in `predict_glmnet()`.
The `predict_<type>()` methods don't run this check. I think generally users are supposed to use `predict(type = <type>)` rather than `predict_<type>()` but the `predict_<type>()` functions are exported. If we think this check is important to have also when directly calling `predict_<type>()`, I'd suggest we add it to the method for `model_fit` objects but since it's not glmnet-specific, I have removed it here. 
`multi_predict()` does not have a central `model_fit` method (because it doesn't apply to all models) so I have left the check in the glmnet-specific method.
The tests for glmnet engines live in extratests, those checks pass locally …

remove check on newdata typo in glmnet functions

---

tests/testthat/_snaps/translate.md
tests/testthat/test_translate.R

The snapshot previously just captured the error message about the missing penalty value, now it shows that `path_values` gets translated to `lambda` as it should.

Fix test on translating `path_values` to `lambda` for glmnet

---

NEWS.md
R/convert_data.R
tests/testthat/test_convert_data.R

Closes #883, more context there!🪲
With CRAN version:
``` r
parsnip:::will_make_matrix(factor("a"))
#> [1] FALSE
parsnip:::will_make_matrix(factor(character()))
#> [1] TRUE
```
With this PR:
``` r
parsnip:::will_make_matrix(factor("a"))
#> [1] FALSE
parsnip:::will_make_matrix(factor(character()))
#> [1] FALSE
```
<sup>Created on 2023-02-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

make `will_make_matrix()` behave consistently for 0-length factors

---

R/glmnet.R
R/linear_reg.R
R/logistic_reg.R
R/poisson_reg.R
R/proportional_hazards.R

closes #891
This PR is to reduce code duplication. I've picked `set_glmnet_penalty_path()` sorta in keeping with `.check_glmnet_penalty*()` (sans the dot, since we don't export it). I think it's a decent name but I'm happy to consider other suggestions, too!

add `set_glmnet_penalty_path()`

---

R/translate.R

This PR adds an early return to the `deharmonize()` helper function and transitions `tibble()` to `new_tibble(list())`.
The modified version, for ease of reprex:
``` r
args <- list(penalty = quo(NULL), mixture = quo(tune()))
arg_key <- 
tibble::tibble(
parsnip = c("penalty", "mixture"), 
original = c("lambda", "alpha"), 
func = list(list(pkg = "dials", fun = "penalty"), 
list(pkg = "dials", fun = "mixture")), 
has_submodel = c(TRUE, FALSE)
)  
deharmonize2 <- function(args, key) {
if (length(args) == 0) {
return(args)
}
if (nrow(key) == 0) {
return(args[integer(0)])
}
parsn <- list(parsnip = names(args), order = seq_along(args))
parsn <- tibble::new_tibble(parsn, nrow = length(args))
merged <-
dplyr::left_join(parsn, key, by = "parsnip") %>%
dplyr::arrange(order) …
```

speed up `deharmonize()` helper

---

R/translate.R
tests/testthat/test_translate.R

This PR speeds up the `get_model_spec()` helper. I'm first just pushing some new tests so we can run checks and ensure that results don't change.
This helper is called once per model specification fit (or translation).
``` r
bt <- bootstraps(mtcars, 100)
bm <- 
bench::mark(
total = 
fit_resamples(linear_reg(), mpg ~ ., bootstraps(mtcars, 100)),
get_model_spec = 
replicate(100, parsnip:::get_model_spec("linear_reg", "regression", "lm")),
check = FALSE
)
#> Warning: Some expressions had a GC in every iteration; so filtering is
#> disabled.
bm
#> # A tibble: 2 × 6
#>   expression          min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>     <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 total              5.2s     5.2s     0.192   73.57MB    10.6 
#> 2 …
```

speed up `get_model_spec()` helper

---

R/aaa_models.R
R/misc.R
man/extension-check-helpers.Rd

The `read_model_info_table()` helper is called 3 times per fit, and is read from file each time.
``` r
bt <- bootstraps(mtcars, 100)
bm <- 
bench::mark(
total = 
fit_resamples(linear_reg(), mpg ~ ., bt),
read_model_info_table = 
replicate(300, parsnip:::read_model_info_table()),
check = FALSE
)
#> Warning: Some expressions had a GC in every iteration; so filtering is
#> disabled.
bm
#> # A tibble: 2 × 6
#>   expression                 min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>            <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 total                    5.94s    5.94s     0.168      57MB     8.92
#> 2 read_model_info_table 215.87ms 219.19ms     4.57     25.1MB     3.04
```
As a percentage of total time, the check takes:
``` r
100 * …
```

`read_model_info_table()` only once

---

NEWS.md
R/mars.R

Closes #251.🏄
With this PR:
``` r
mars(
mode = "classification",
num_terms = 1,
prod_degree = 1,
prune_method = "backward"
) %>% 
set_engine("earth") %>% 
fit(Species ~ ., iris)
#> Loading required package: Formula
#> Loading required package: plotmo
#> Loading required package: plotrix
#> Loading required package: TeachingDemos
#> 
#> GLM (family binomial, link logit):
#>            nulldev  df       dev  df   devratio     AIC iters converged
#> setosa     190.954 149   190.954 149          0     193     4         1
#> versicolor 190.954 149   190.954 149          0     193     4         1
#> virginica  190.954 149   190.954 149          0     193     4         1
#> 
#> Earth selected 1 of 15 terms, and 0 of 4 predictors (nprune=1)
#> Termination …
```

`load_libs()` with `engine == "earth"`

---

NEWS.md
R/nearest_neighbor.R

Closes #264. :) Same story as in #913.
``` r
mtcars$am <- as.factor(mtcars$am)
mtcars$cyl <- as.factor(mtcars$cyl)
nearest_neighbor() %>%  
set_engine("kknn") %>%
fit(am ~ ., data = mtcars)
#> 
#> 
#> Call:
#> kknn::train.kknn(formula = am ~ ., data = data, ks = min_rows(5,     data, 5))
#> 
#> Type of response variable: nominal
#> Minimal misclassification: 0.09375
#> Best kernel: optimal
#> Best k: 5
```
<sup>Created on 2023-03-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

`load_libs()` with `engine == "kknn"` and factor predictors

---

NEWS.md
R/misc.R
tests/testthat/_snaps/logistic_reg.md
tests/testthat/test_logistic_reg.R

Closes #545.🐧 Warns rather than errors since some engines bin the non-first-level outcome levels as the non-event.
Locating this check inside of `check_outcome` rather than `translate.logistic_reg()` since we don't yet have access to the outcome at the point. :/

warn with >2 levels on `logistic_reg()` fit

---

R/predict.R

closes  #263
The main part was done in #268 but since the issue was still open, this PR now extends it to newer prediction types.

`format_<prediction type>()` functions only format when necessary

---

R/predict.R

This PR makes `check_pred_type()` equally verbose about the prediction type for censored regression as it already is for classification.

Be more verbose about prediction types in `check_pred_type()`

---

DESCRIPTION
NEWS.md

closes  #908
revdeps look fine
```
revdepcheck::cloud_summary()
ℹ Syncing results to revdep/cloud.noindex/1f0903e8-a59b-44bf-832a-8c7bd08538da
ℹ Comparing results              
✔ additive 0.0.5                         ── E: 1     | W: 0     | N: 0    
✔ agua 0.1.2                             ── E: 1     | W: 0     | N: 0    
E autostats 0.4.0                        ── E: 1/1   | W: 0/0   | N: 0/0  
✔ baguette 1.0.0                         ── E: 2     | W: 0     | N: 1    
I bayesian 0.0.9                         ── E: 1     | W: 0     | N: 1    
✔ bonsai 0.2.1                           ── E: 0     | W: 0     | N: 0    
E broom.helpers 1.12.0                   ── E: 0/0   | W: 0/0   | N: 1/1  
✔ bundle 0.1.0                           ── E: 0     | W: 0     | N: 0    
✔ butcher 0.3.2 …
```

bump minimum version for R

---

R/tunable.R

``` r
```
`tunable.model_spec()` is called once per resample fit, and several times when tuning hyperparameters.
``` r
lr <- linear_reg()
bm <- 
bench::mark(
total = fit_resamples(lr, mpg ~ ., bootstraps(mtcars, 100)),
tunable = replicate(100, tunable(lr)),
check = FALSE
)
#> Warning: Some expressions had a GC in every iteration; so filtering is
#> disabled.
bm
#> # A tibble: 2 × 6
#> 1 total         5.06s    5.06s     0.198   47.69MB     8.11
#> 2 tunable    488.02ms 488.49ms     2.05     3.32MB     8.19
```
As a percentage of total time, the check takes:
``` r
100 * as.numeric(bm$median[2]) / as.numeric(bm$median[1])
#> [1] 9.657983
```
The …

speed up `tunable.model_spec()`

---

R/tune_args.R

`tune_tbl()` is called each resample fit, and is a light wrapper around `tibble::tibble()`. The function is only called inside of `tune_args()`, so we know what kinds of inputs the helper will receive:
<https://github.com/tidymodels/parsnip/blob/d8f273cd3eeac3cb2c130109a785fb291bc9e58c/R/tune_args.R#L21-L29>
``` r
bm <- 
bench::mark(
total = fit_resamples(linear_reg(), mpg ~ ., bootstraps(mtcars, 100)),
tune_tbl = replicate(100, parsnip:::tune_tbl()),
check = FALSE
)
bm
#> # A tibble: 2 × 6
#> 1 total         3.25s    3.25s     0.308    47.7MB     8.92
#> 2 tune_tbl    43.77ms  47.91ms    22.6        77KB    11.3
```
As a percentage of total time, the helper takes: …

speed up `tune_tbl()` helper

---

R/aaa_models.R

Same idea as https://github.com/tidymodels/tune/pull/637. :) Only implemented in model registration code—this doesn't have much of a user-facing effect, but makes `devtools::load_all()` feel a bit snappier.
``` r
bench::mark(
load_all = devtools::load_all()
)
#> ℹ Loading parsnip
#> # A tibble: 1 × 13
#>   expression      min   median itr/s…¹ mem_a…² gc/se…³ n_itr  n_gc total…⁴
#>   <bch:expr> <bch:tm> <bch:tm>   <dbl> <bch:b>   <dbl> <int> <dbl> <bch:t>
#> 1 load_all       1.9s     1.9s   0.526  26.6MB    3.68     1     7    1.9s
#> # … with 4 more variables: result <list>, memory <list>, time <list>,
#> #   gc <list>, and abbreviated variable names ¹​`itr/sec`, ²​mem_alloc,
#> #   ³​`gc/sec`, ⁴​total_time
#> # ℹ Use `colnames()` to see all variable names
```
With this PR:
``` r
#> # A …
```

audit uses of `tibble()` and `as_tibble()`

---

DESCRIPTION
R/glmnet-engines.R

This refactoring doesn't change how the functions work but aims to increase readability. The function for logistic regression models already uses this style.
Extratests includes tests on the exact format of predictions (and those run fine).

Refactor formatting functions for glmnet methods for `multi_predict()`

---

R/aaa_models.R

We've managed to cut down on calls to `check_spec_mode_engine_val()` in many places, though in most cases we're dropped into there we can still return early. It's hard to troubleshoot exactly what went wrong with misspecified specifications, but since the parsnip model environment is our ground truth for when a specification _is_ well-defined, we should first look to it to see if we can skip the remaining checks. For quick fits like `stats::lm()` on a small dataset, this makes parsnip about twice as fast!😮
With `main` dev:
``` r
bench::mark(
total = fit(linear_reg(), mpg ~ ., mtcars),
iterations = 25
)
#> 1 total        7.65ms …
```

return early when possible in spec checking

---

R/misc.R

My old helper was slow🦥 Instead of joining, we can perform the filtering on the separate datasets, and with vctrs instead of dplyr. For a quick model fit on a small dataset, this cuts down fit time by ~22%!
With `main` dev:
``` r
bench::mark(
total = fit(linear_reg(), mpg ~ ., mtcars),
iterations = 25
)
#> 1 total        7.65ms   8.04ms      120.    7.19MB     67.6
```
With this PR:
``` r
#> 1 total        6.09ms   6.28ms      155.    7.12MB     60.3
```
<sup>Created on 2023-03-17 …

speed up `spec_is_possible()` helper

---

R/predict.R

We're now good to go on the worst-case overhead of `fit()`, though this step in `predict()` introduces the last big slowdown causing the overhead in evaluation time in the causal estimate bootstrapping example. `as_tibble()` takes a bit of time, but the deprecation warning in `map_dfr()` especially slows us down.
With `main` dev:
``` r
lr <- fit(logistic_reg(), Class ~ ., two_class_dat)
bench::mark(
old = predict(lr, two_class_dat, type = "prob")
)
#> 1 old          3.01ms   3.12ms      305.    3.62MB     6.27
```
With this PR:
``` r
#> …
```

speed up `format_classprobs()` helper

---

R/predict.R

Together with #934, puts us under 100% overhead in the causal estimate bootstrapping example. :)
With `main` dev:
``` r
lr <- fit(logistic_reg(), Class ~ ., two_class_dat)
bench::mark(
old = predict(lr, two_class_dat, type = "prob")
)
#> 1 old          3.01ms   3.12ms      305.    3.62MB     6.27
```
With this PR:
``` r
#> 1 new          2.14ms   2.44ms      398.   84.78KB     6.19
```
<sup>Created on 2023-03-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

speed up `prepare_data()` helper

---

DESCRIPTION
R/predict.R
R/predict_hazard.R
R/predict_survival.R
man/other_predict.Rd
man/predict.model_fit.Rd

Closes #892
This PR deprecates the `time` argument to the prediction functions in favor of the `eval_time` argument name.
- `predict()` only takes this argument in the ellipsis, so I updated only the documentation. I replaced `time` with `eval_time`, i.e. there is no mention of any deprecation but instead a direct swap. Should this talk about deprecation as well? I was trying not to overload that help page since it contains so much already.
- `predict_survival()` and `predict_hazard()` both had a `time` argument. Now they have both `time` and `eval_time` as arguments, and `time` is deprecated, including updates to the documentation.
This PR starts the deprecation at `deprecate_warn()` rather than a soft-deprecation. Does that sound good?
Tests on this deprecation are going to have to sit …

`time` to `eval_time`

---

DESCRIPTION
R/glmnet-engines.R

Doing a quick speed audit on stacks right now to see if there's any low-hanging fruit, and this call to `packageVersion()` took up a pretty substantial amount of time. This PR proposes bumping the minimum dplyr version and writing out that conditional statement.
EDIT: Couldn't find it at first, but just confirmed we thumbs-upped a bump in minimum dplyr version in `#tidymodels-internal`.

bump minimum dplyr version

---

R/adds.R
R/autoplot.R
R/boost_tree.R
R/mars.R
R/misc.R
R/mlp.R
R/surv_reg.R

I noticed there are a couple of places where we use `:` that could be replaced with `seq_*()` to make the code a little more robust

don't use colon programatically

---

NEWS.md
R/engines.R
R/fit_control.R
R/surv_reg.R
R/varying.R
man/surv_reg.Rd

It has now been at least a year since each of these were soft-deprecated. :)

transition v0.1.6 and v0.1.8 `soft`-deprecations to `warn`

---

DESCRIPTION
R/ipcw.R
R/predict.R
R/predict_hazard.R
R/predict_survival.R
man/censoring_weights.Rd
man/predict.model_fit.Rd
tests/testthat/_snaps/ipcw.md
tests/testthat/_snaps/translate.md
tests/testthat/test-ipcw.R

The current code unnests the data. This is a problem if we also are using static predictions (like the predicted event time). 
This PR keeps the list format and adds the required columns to each tibble within the list.

Keep IPCW results in the list column format predicted by the predict() methods

---

NEWS.md

Adds some structure, clarifies wordings, note some undocumented changes.

workshop NEWS

---

R/required_pkgs.R

With main dev:
``` r
set.seed(1)
bench::mark(
old = 
fit_resamples(
linear_reg(),
mpg ~ .,
bootstraps(mtcars)
)
)
#> 1 old           210ms    213ms      4.61    14.2MB     7.68
```
With this PR:
``` r
#> 1 new           201ms    204ms      4.77    14.1MB     7.96
```
<sup>Created on 2023-05-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

transition to `vec_slice()` in `get_pkgs()`

---

DESCRIPTION
NEWS.md
R/augment.R
R/survival-censoring-weights.R
man/augment.Rd
tests/testthat/test_augment.R

Enables `augment()` for models with mode `"censored regression"`. 
This also moves columns with `.pred*` and `.resid` to the left-most position.

survival model fit augmentation

---

R/standalone-survival.R

This is possibly a smidge easier to read in commit-order instead of aggregated:
- the first commit just moves functions into an order in which they build on each other, for readability
- the second commit adds a call arg to functions that may call `rlang::abort()` so that we can pass the call through
The tests are in extratest and don't change because they either don't capture those error messages (yet) or because the call does not get passed on (yet).

Add `call` arg to checking functions in standalone-survival

---

R/survival-censoring-weights.R
tests/testthat/_snaps/survival-censoring-weights.md
tests/testthat/test-survival-censoring-weights.R

This PR workshops the tests for `trunc_prob()` and `.filter_eval_time()` to make it easier to see what we're testing for.

Workshop tests on censoring weights

---

tests/testthat/test-survival-censoring-weights.R

I think the test removed in this PR is mainly to test aspects which are already covered by the other test on `trunc_probs()`. I'll comment with links :)

Remove redundant test on `trunc_probs()`

---

NEWS.md
R/bart.R
R/bart_data.R

closes  #976
``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
set.seed(1)
bt_cls_fit <- 
parsnip::bart() %>% 
set_mode("classification") %>% 
set_engine("dbarts") %>% 
fit(Class ~ ., data = two_class_dat)
set.seed(2)
bind_cols(
predict(bt_cls_fit, two_class_dat, type = "prob"),
predict(bt_cls_fit, two_class_dat, type = "pred_int", std_error = TRUE)
) %>%
select(-contains(c("lower", "upper")))
#> # A tibble: 791 × 3
#>    .pred_Class1 .pred_Class2 .std_error
#>           <dbl>        <dbl>      <dbl>
#>  1       0.351         0.649      0.478 …
```

dbarts: add standard error for interval predictions

---

R/nullmodel.R
man/null_model.Rd

This PR aligns the `mode` argument documentation for `null_model()` with its registered modes:
https://github.com/tidymodels/parsnip/blob/a85e5083de0d1ec8087678cf21580690a37da81b/R/nullmodel_data.R#L8-L9
...and the help-file's model description:
https://github.com/tidymodels/parsnip/blob/a85e5083de0d1ec8087678cf21580690a37da81b/R/nullmodel.R#L130-L131
Closes #982.

correct documented `mode`s for `null_model()`

---

NEWS.md
R/linear_reg_data.R
tests/testthat/test_linear_reg.R

This PR aims to close https://github.com/tidymodels/parsnip/issues/985.
This bug only appears on 4.3 and newer as that is when `predict.lm()` got the new `rankdeficient` argument.
I picked this solution as it would create backwards compatibility.

Fix bug for 4.3 where rank deficient prediction from `lm` model gave different column names

---

R/augment.R
R/predict.R
man/augment.Rd
man/predict.model_fit.Rd

closes #979
I've not included links to `.censoring_weights_graf()` like in the issue description because that function is `@keyword internal` and I think it would be too much detail on the predict help page. If we think it's super important to talk about that internal function in the docs then I would add it to the help page for `augment()` (and consider making the function not internal) - but I tend to think that `augment()` is the right place to point a user to.

add to `predict()` docs how to get the IPCW

---

DESCRIPTION
R/augment.R

What the title says. to close https://github.com/tidymodels/parsnip/issues/988.
I didn't add anything to `NEWS` since it already has a bullet that says `augment() now works for censored regression models.`

error if `eval_time` is needed and missing when calling augment()

---

NEWS.md
R/boost_tree.R
tests/testthat/test_boost_tree.R

What the title says. This bug was reported on StackOverflow here https://stackoverflow.com/questions/76782839/error-fitting-xgboost-classification-models-with-single-predictor
The fix was to [add drop = FALSE to matrix subsetting in as_xgb_data()](https://github.com/tidymodels/parsnip/commit/6fecfb83a6c83054b2e50f391fc732fa8992b9b7)

 Fixed bug where `boost_tree()` models couldn't be fit with 1 predictor if `validation` argument was used.

---

NEWS.md
R/misc.R
tests/testthat/_snaps/misc.md
tests/testthat/test_misc.R

improve error when outcome is missing

---

NEWS.md
man/rmd/mlp_brulee.Rmd
man/rmd/mlp_brulee.md

closes  #1018
Looks like the values for `learn_rate` and `epochs` got swapped. The new values are the default values in {brulee}.

fix default vaulues for `mlp(engine = "brulee")`

---

R/boost_tree.R
man/boost_tree.Rd
man/parsnip_update.Rd
man/rmd/boost_tree_xgboost.Rmd
man/rmd/boost_tree_xgboost.md
man/rule_fit.Rd

Document what `mtry = NULL` means for xgboost

---

DESCRIPTION
NEWS.md
R/standalone-survival.R
tests/testthat/test-survival-censoring-weights.R

Closes #1023
See https://github.com/tidymodels/workflows/pull/200 and https://github.com/tidymodels/extratests/issues/110

ensure survival vectors are unnamed for #1023

---

NEWS.md
R/survival-censoring-model.R

To close #965
I removed `new_data` from the function signature since it is swalloed up by `...` anyways. I also added a little warning, since using `new_data` for predict methods are quite a common action
``` r
library(censored)
mod_fit <-
survival_reg() %>%
fit(Surv(time, status) ~ age + sex, data = lung)
pred_newdata <- predict(mod_fit$censor_probs, time = (7:10) * 100,
new_data = mtcars)
#> Warning: `new_data` is ignored when predicting on `censoring_model_reverse_km()` models
#> as it doesn't affect the result.
```
<sup>Created on 2023-11-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

remove new_data argument from predict.censoring_model_reverse_km()

---

DESCRIPTION
R/standalone-survival.R

to close https://github.com/tidymodels/parsnip/issues/1025
``` r
times <- seq(1, 100, length.out = 5)
times2 <- seq(100, 200, length.out = 5)
events <- c(1, 0, 1, 0, 1)
intv_c <- survival::Surv(times, times2, events, type = "interval")
count_c <- survival::Surv(times, times2, events)
parsnip:::.extract_surv_time(intv_c[1])
#> # A tibble: 2 × 1
#>     res
#>   <dbl>
#> 1     1
#> 2     1
parsnip:::.extract_surv_time(count_c[1])
#> # A tibble: 2 × 1
#>     res
#>   <dbl>
#> 1     1
#> 2   100
```
<sup>Created on 2023-11-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

make .extract_surv_time() work correctly for 1-row output

---

NEWS.md

`censoring_model_reverse_km` is the class of the objects returned by `reverse_km()`. Not sure if this means we should change the name of either but for now this is a very light touch-up on the NEWS so that it's correct.

Touch-up NEWS

---

DESCRIPTION
NEWS.md
R/convert_data.R
R/fit_helpers.R

closes  #1032
parsnip captures in its encodings ([example](https://github.com/tidymodels/parsnip/blob/d65dde2185c02f30325b080faf5163bb0c0ede93/R/linear_reg_data.R#L28-L29)) what to do about the intercept for a specific engine. In a "pure parsnip use case" this only matters when parsnip has to convert data between its own formula interface and the engine's matrix interface, covered in `.convert_form_to_xy()`. (The reason why we might have both `include_intercept` and `remove_intercept` as `TRUE` is because the indicators for factor variables are affected by the absence/presence of the intercept.)
When a parsnip model is used inside of a workflow together with a formula as the preprocessor, the encodings matter again (they do not matter for other kinds of preprocessors):
In workflow's pre …

Remove intercept coming from workflows based on engine encodings

---

R/fit_helpers.R

#1033 added an encodings-based removal of the intercept column to `form_form()`, which broke the spark case-weights tests in extratests.
So this PR moves that step so that we don't try this for spark data.

Don't modify spark data in `form_form()`

---

DESCRIPTION
NEWS.md
R/survival-censoring-model.R

To close https://github.com/tidymodels/parsnip/issues/1029
Tests in extratests: https://github.com/tidymodels/extratests/pull/153

Check dots empty censoring model

---

DESCRIPTION
NAMESPACE
R/survival-censoring-weights.R
man/censoring_weights.Rd

to close https://github.com/tidymodels/parsnip/issues/968
Paired {workflows} PR: https://github.com/tidymodels/workflows/pull/213
There are 4 possible scenarios:
This is fine!
Happens if `parsnip < 1.1.1.9007` and `workflows < 1.1.3.9001`, which is another way of saying that both packages are installed before Dec 12.
This is fine!
Happens if `parsnip >= 1.1.1.9007` and `workflows >= 1.1.3.9001`, which is another way of saying that both packages are installed after Dec 12 (or whenever the PRs are merged in.
This is not good.
Would need `parsnip < 1.1.1.9007` and `workflows >= 1.1.3.9001`. Which can't happen as workflows `1.1.3.9001` requires `parsnip >= 1.1.1.9007`. So we are good here.
##`.censoring_weights_graf.workflow()` isn't exported
Would happen if `parsnip >= 1.1.1.9007` and …

Move .censoring weights graf.workflow

---

R/bag_tree.R
R/bart.R
R/boost_tree.R
R/c5_rules.R
R/cubist_rules.R
R/decision_tree.R
R/discrim_flexible.R
R/discrim_linear.R
R/discrim_quad.R
R/discrim_regularized.R
R/gen_additive_mod.R
R/mars.R
R/mlp.R
R/naive_Bayes.R
R/nearest_neighbor.R
R/pls.R
R/poisson_reg.R
R/proportional_hazards.R
R/rand_forest.R
R/rule_fit.R
R/surv_reg.R
R/survival_reg.R
R/svm_linear.R
R/svm_poly.R
R/svm_rbf.R
man/bag_tree.Rd
man/boost_tree.Rd
man/decision_tree.Rd
man/rand_forest.Rd

To close https://github.com/tidymodels/parsnip/issues/661.
I switched the default to nearest neighbor for classification/regression

document censored regression as a possible mode

---

R/standalone-survival.R
tests/testthat/_snaps/standalone-survival.md

To close #967 
I went all in! it is super fancy now
``` r
times_duplicated <- c(1:9, 1:4, NA, Inf, -4, -4, -3)
parsnip:::.filter_eval_time(times_duplicated)
#> Warning: There were 9 inappropriate evaluation time points that were removed. They were:
#> • 1 missing value.
#> • 1 infinite value.
#> • 3 negative values.
#> • 4 duplicate values.
#> [1] 1 2 3 4 5 6 7 8 9
```

give .filter_eval_time() more informative warning

---

NEWS.md
R/mlp_data.R

Closes #1050.🏄
`stop_iter` had been mistakenly registered as a model argument for `mlp()`.
``` r
set.seed(1)
mlp(hidden_units = 5, epochs = 100) %>% 
set_engine("brulee", stop_iter = 5)  %>% 
set_mode("regression") %>%
fit(price ~ latitude + longitude, data = Sacramento)
#> 
#> Multilayer perceptron
#> 
#> relu activation
#> 5 hidden units,  21 model parameters
#> 932 samples, 2 features, numeric outcome 
#> weight decay: 0.001 
#> dropout proportion: 0 
#> batch size: 839 
#> learn rate: 0.01 
#> scaled validation loss after 100 epochs: 1.29
set.seed(1)
res <- 
tune_grid(
mlp(hidden_units = 3, epochs = 50) %>% 
set_engine("brulee", stop_iter = tune())  %>% 
set_mode("regression"),
price ~ latitude + longitude,
vfold_cv(Sacramento, v = 5),
grid …
```

enable setting `stop_iter` with brulee `mlp()`

---

NEWS.md
R/linear_reg_data.R
R/logistic_reg_data.R
R/mlp_data.R
R/multinom_reg_data.R

Closes #1052. These are all brulee-related; the two remaining ones are in bonsai. :)

remove registrations for engine arguments

---

NEWS.md
R/convert_data.R
R/fit.R
R/fit_helpers.R
tests/testthat/test_fit_interfaces.R

We use `is.atomic()` in `check_outcome()` rather than `is.vector()` as it more often aligns with what we mean when we're checking for outcome types. I've transitioned those type checks in a few more places. Closes #1060, closes #1061.

handle attributes on outcome columns

---

NEWS.md
R/mlp.R
tests/testthat/test_mlp.R

Closes #1019 
With the new brulee on CRAN, this lets the engine packages check for proper argument values.

Activation checks

---

NEWS.md
R/predict_hazard.R
R/predict_survival.R

Closes #1039 
Tested on extratests via `devtools::test(filter = "(survival)|(censor)")`

changes for #1039

---

R/predict_hazard.R
R/predict_linear_pred.R
R/predict_numeric.R
R/predict_survival.R
R/predict_time.R

#1066 removed the extra arguments we were adding to the prediction call so this PR updates the corresponding comment to the same one used across other prediction types. (Bonus: fixing some formatting while I was looking at those lines of code.)

Sync code/comment patterns across prediction types

---

R/translate.R

This `env_obj` isn't used elsewhere in the function and accounts for a decent chunk of the overhead in this example.
With dev parsnip:
``` r
bench::mark(fit = fit(linear_reg(), mpg ~ ., mtcars))
#> 1 fit          1.51ms   1.78ms      547.    3.76MB     32.5
```
With this PR:
``` r
bench::mark(fit = fit(linear_reg(), mpg ~ ., mtcars))
#> 1 fit          1.41ms   1.51ms      642.    3.75MB     36.7
```
<sup>Created on 2024-02-26 with [reprex …

address slowdown in `get_model_spec()`

---

R/fit_helpers.R

On `main` dev:
```r
bench::mark(
fit = fit_xy(linear_reg(), mtcars[2:11], mtcars[1])
)
#> 1 fit          1.76ms   2.07ms      473.    3.95MB     32.3
```
With this PR:
``` r
bench::mark(
fit = fit_xy(linear_reg(), mtcars[2:11], mtcars[1])
)
#> 1 fit          1.27ms   1.48ms      656.    2.79MB     31.7
```
<sup>Created on 2024-02-27 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

address slowdown in `fit_xy()`

---

.github/workflows/R-CMD-check.yaml
DESCRIPTION
tests/testthat/test_fit_interfaces.R

Some minimal testing to alert us when we've allowed additional "overhead" to creep in. A more true test of overhead would test differences rather than ratios, but those numbers are largely system-dependent.
My intent here is not that we'd automatically reject a PR that causes this test to fail, but to let us know when a PR changes these ratios and give us a chance to consider whether the slowdown is worth the benefit or ought to be addressed.

test parsnip "overhead"

---

man/details_boost_tree_xgboost.Rd
man/rmd/boost_tree_xgboost.Rmd
man/rmd/boost_tree_xgboost.md

document xgboost case weight support

---

R/aaa_models.R
tests/testthat/_snaps/registration.md
tests/testthat/test_registration.R

clarify case weight support in `show_model_info()`

---

R/fit_helpers.R

Closes #1109. Note that `system.time()` is also just based on `proc.time()` subtraction with an exit handler for failures in `expr`. :) This implementation now matches the analogous one from recipes.

address `Timing stopped at` exit handler on engine fit

---

.github/workflows/R-CMD-check.yaml
.github/workflows/pkgdown.yaml
.github/workflows/test-coverage.yaml

to close https://github.com/tidymodels/parsnip/issues/1118

increase miniconda python version

---

man/rmd/mlp_brulee.Rmd
man/rmd/mlp_brulee.md

The default parameter for `penalty` in the docs is incorrect. This is a comically small PR, but it did trip me up this week thinking the default was 0 when it wasn't.
Here is some quick reprex proof via `parsnip::` and via `brulee::` itself (see 'weight decay' value):
``` r
data <- modeldata::two_class_dat
rec <-
data |>
recipes::recipe(Class ~ .)
mod <-
parsnip::mlp() |>
parsnip::set_engine("brulee") |>
parsnip::set_mode("classification")
wf <-
workflows::workflow() |>
workflows::add_recipe(rec) |>
workflows::add_model(mod)
wf |>
parsnip::fit(data = data)
#> ══ Workflow [trained] ══════════════════════════════════════════════════════════
#> Preprocessor: Recipe
#> Model: mlp()
#> 
#> ── Preprocessor ────────────────────────────────────────────────────────────────
#> 0 Recipe Steps
#> 
#> …
```

Doc Fix: `mlp_brulee()`

---

man/details_mlp_brulee.Rd

Follow up to #1122 , PR didn't include the .Rd file needed for building the site. This should fix the issue.

run `devtools::document()` for .Rd file

---

R/predict_class.R
R/predict_classprob.R
R/predict_numeric.R
R/predict_time.R
tests/testthat/test-predict_formats.R

Fixes `R/predict_class.R`, `R/predict_classprob.R`, `R/predict_numeric.R`, and `R/predict_time.R`

Use cli instead of rlang for abort and warn, Fixes #1141

---

R/glmnet-engines.R
R/logistic_reg.R
R/mars.R
R/mlp.R
tests/testthat/_snaps/translate.md

fixes #1140
@wright13
Co-author-by: Sarah Wright <sarah_wright@nps_gov>

change rlang abort to cli_abort

---

R/predict.R

updated rlang messages in the predict functions to use cli. 

---

R/nearest_neighbor_data.R
R/rand_forest.R
R/rand_forest_data.R
R/svm_linear.R
R/svm_rbf_data.R

Closes #1142. Transitions conditions from rlang to cli in the files noted in the linked issue!

transition to cli from rlang

---

man/rmd/bart_dbarts.Rmd
man/rmd/mars_earth.Rmd
man/rmd/mlp_brulee.Rmd
man/rmd/nearest_neighbor_kknn.Rmd
man/rmd/svm_linear_LiblineaR.Rmd
man/rmd/svm_linear_kernlab.Rmd
man/rmd/svm_poly_kernlab.Rmd
man/rmd/svm_rbf_kernlab.Rmd

Documents {parsnip}'s default ranges for tunable parameter via `set_model_arg()`. Also removes documentation for mars model earth engine that described non-implemented functionality for `num_terms`.
Fixes #954 
Note that this does not include tunable parameters where this is set by another means.

Document default ranges for tunable parameters

---

NEWS.md
R/engine_docs.R
R/install_packages.R
man/knit_engine_docs.Rd

Closes #1156 
Updates the existing (internal) `install_engine_packages()` and calls it when `knir_engine_docs()` is executed.

Engine and extension installs

---

tests/testthat/test-fit_interfaces.R

Maybe every three or four times we run the parsnip overhead unit tests on the macOS-release and ubuntu-oldrel-4 runners, we see a failure. We should figure out how to make that happen much, much less often.
Starting out by making the error message more informative to see whether we're "close" to the limit.

refine parsnip overhead test

---

NEWS.md
R/fit_helpers.R
R/predict.R
tests/testthat/test-predict_formats.R

to close #1166.
This bug happened because we don't know the name of the outcome(s) `y` when using `fit_xy()` because it is often a nameless vector. So instead, what I tried to do was to save the names of the `x` and subset with those when appropriate. 
This is NOT a xgboost issue. it is just that xgboost complains more loudly than other engines. 
``` r
spec <- boost_tree() %>%
set_mode("regression") %>%
set_engine("xgboost")
lm_fit <- fit(spec, mpg ~ ., data = mtcars)
predict(lm_fit, mtcars)
#> # A tibble: 32 × 1
#>    .pred
#>    <dbl>
#>  1  20.9
#>  2  20.9
#>  3  22.6
#>  4  21.0
#>  5  18.4
#>  6  18.1
#>  7  14.2
#>  8  23.7
#>  9  22.4
#> 10  18.9
#> # ℹ 22 more rows
lm_fit <- fit_xy(spec, x = mtcars[, -1], y = mtcars[, 1])
predict(lm_fit, mtcars)
#> # A tibble: 32 …
```

save x column names from fit_xy()

---

NEWS.md
R/arguments.R
R/convert_data.R
R/fit.R
R/fit_helpers.R
R/sparsevctrs.R
tests/testthat/_snaps/sparsevctrs.md
tests/testthat/test-sparsevctrs.R

Ref: https://github.com/tidymodels/parsnip/issues/1125
This PR is in essence very similar to https://github.com/tidymodels/parsnip/pull/1121
`fit_xy()`
`fit()`

Allow sparse tibbles in `fit()` and `fit_xy()`

---

R/sparsevctrs.R

Noticed this when reviewing #1167 but it's unrelated to that PR. If we do the "cheap" side of the `&&` first, we can cut down on the overhead of "not converting to sparse when we don't want to." :)
Before this PR:
```
d <- data.frame(sparse = "no")
lr <- linear_reg()
bench::mark(
to_sparse_data_frame(d, lr)
)
#> # A tibble: 1 × 13
#>   expression              min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
#>   <bch:expr>           <bch:> <bch:>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>
#> 1 to_sparse_data_fram… 26.9µs 28.5µs    33538.        0B     16.8  9995     5      298ms <df>  
```
Now:
```
#> # A tibble: 1 × 13
#>   expression              min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result
#>   <bch:expr>           <bch:> …
```

reduce overhead of `to_sparse_data_frame()`

---

NEWS.md
R/fit.R
R/predict.R
R/sparsevctrs.R
tests/testthat/_snaps/sparsevctrs.md
tests/testthat/test-sparsevctrs.R

Ref: https://github.com/tidymodels/parsnip/issues/1125
Predicting with a sparse matrix already works, as long as the engine supports it. but is now tested with this PR.
Waiting for https://github.com/tidymodels/parsnip/pull/1165 to be merged so I can use the helper function defined there to give better error message when sparse data is passed to model that doesn't support it

Make sure sparse matrices can be used with `predict()`

---

R/convert_data.R
tests/testthat/test-sparsevctrs.R

Ref: https://github.com/tidymodels/parsnip/issues/1125
xgboost is the only model that supports sparse data that has a non-standard interface. This PR makes it so those special connections still work. And tests them.

make sure xgboost works with sparse data

---

R/autoplot.R
R/control_parsnip.R
R/required_pkgs.R
R/tidy_glmnet.R
R/tune_args.R

use type checkers in remaining functions

---

R/convert_data.R
R/fit.R
R/misc.R
tests/testthat/_snaps/fit_interfaces.md

use type checkers in `fit.R`

---

R/aaa_models.R
R/predict_classprob.R
tests/testthat/_snaps/registration.md
tests/testthat/_snaps/svm_linear.md

use type checkers in `aaa_models.R`

---

tests/testthat/test-boost_tree_C5.0.R
tests/testthat/test-boost_tree_xgboost.R
tests/testthat/test-case-weights.R
tests/testthat/test-descriptors.R
tests/testthat/test-extract.R
tests/testthat/test-fit_interfaces.R
tests/testthat/test-gen_additive_model.R
tests/testthat/test-glm_grouped.R
tests/testthat/test-linear_reg.R
tests/testthat/test-linear_reg_keras.R
tests/testthat/test-logistic_reg.R
tests/testthat/test-logistic_reg_keras.R
tests/testthat/test-mars.R
tests/testthat/test-misc.R
tests/testthat/test-mlp_keras.R
tests/testthat/test-mlp_nnet.R
tests/testthat/test-multinom_reg_keras.R
tests/testthat/test-multinom_reg_nnet.R
tests/testthat/test-nearest_neighbor_kknn.R
tests/testthat/test-nullmodel.R
tests/testthat/test-packages.R
tests/testthat/test-partykit.R
tests/testthat/test-predict_formats.R
tests/testthat/test-rand_forest_ranger.R
tests/testthat/test-re_registration.R
tests/testthat/test-surv_reg_flexsurv.R
tests/testthat/test-surv_reg_survreg.R
tests/testthat/test-svm_linear.R
tests/testthat/test-svm_poly.R
tests/testthat/test-svm_rbf.R

Related to #1096 but does not close—these are just the cases where `regexp = NA`, i.e. we're testing that there's no error. For all but one case, we can actually test the more stricter version, that there is no condition.

`expect_error(regexp = NA)` -> `expect_no_condition()`

---

R/tidy_glmnet.R

https://github.com/tidymodels/parsnip/commit/227ab92dfb803f5a6f42373e30cc15f9332712cd resulted in a [few new failures on extratests](https://github.com/tidymodels/extratests/actions/runs/10786271230/job/29912882661#step:8:381):
```
══ Failed ══════════════════════════════════════════════════════════════════════
── 1. Error ('test-encodings-glmnet.R:18:3'): parsnip models with formula interf
Error in `dimnames(x) <- dn`: length of 'dimnames' [2] not equal to array extent
Backtrace:
▆
1. ├─generics::tidy(parsnip_form_fit) at test-encodings-glmnet.R:18:3
2. └─parsnip:::tidy._elnet(parsnip_form_fit)
3.   └─parsnip:::tidy_glmnet(x, penalty) at parsnip/R/tidy_glmnet.R:14:3
4.     └─parsnip:::get_glmn_coefs(x$fit, penalty = penalty) at parsnip/R/tidy_glmnet.R:62:3
5. …
```

restore `tidy.glmnet(penalty)` default

---

NEWS.md
R/convert_data.R
R/predict.R
tests/testthat/_snaps/sparsevctrs.md
tests/testthat/helper-objects.R
tests/testthat/test-sparsevctrs.R

All sparsvctrs tests now have option set such that unintentional materialization results in an error.
In addition, we now error on formula interface for sparse data, due to the `model.matrix()` issue we are running into

Stricter sparsevctrs tests

---

NEWS.md
R/predict.R
R/predict_quantile.R
R/surv_reg_data.R
man/other_predict.Rd
man/set_args.Rd
tests/testthat/_snaps/linear_reg_quantreg.md
tests/testthat/test-linear_reg_quantreg.R
tests/testthat/test-surv_reg_survreg.R

For #1203
After this, we will 
- merge the `quantile-mode` branch to main,
- update GHA for the extra branch, and 
- will create a PR for censored with updates to those engines.

Change to `quantile` argument to `quantile levels`

---

R/descriptors.R
R/misc.R
tests/testthat/_snaps/boost_tree_xgboost.md
tests/testthat/_snaps/linear_reg.md
tests/testthat/_snaps/logistic_reg.md
tests/testthat/_snaps/mars.md
tests/testthat/_snaps/misc.md
tests/testthat/_snaps/nearest_neighbor_kknn.md
tests/testthat/_snaps/predict_formats.md
tests/testthat/_snaps/rand_forest_ranger.md
tests/testthat/_snaps/sparsevctrs.md
tests/testthat/test-boost_tree_xgboost.R
tests/testthat/test-mars.R
tests/testthat/test-misc.R
tests/testthat/test-nearest_neighbor_kknn.R
tests/testthat/test-rand_forest_ranger.R
tests/testthat/test-sparsevctrs.R

Mostly data descriptors and outcome checking. 
The PR also removes a few redundant tests of `fit.model_spec()` that probably came about form me copy/pasting in the early days.

A few missing cli error conversions

---

R/arguments.R
tests/testthat/_snaps/arguments.md
tests/testthat/_snaps/mlp.md
tests/testthat/_snaps/multinom_reg.md
tests/testthat/_snaps/nullmodel.md
tests/testthat/test-arguments.R
tests/testthat/test-mlp.R
tests/testthat/test-multinom_reg.R
tests/testthat/test-nullmodel.R

I came across this warning while spring cleaning bonsai and felt that it was reasonable that we tested for it but not that we screenshotted it. This PR adds a warning subclass and corrects pluralization in the message.

workshop protected arguments warning

---

NEWS.md
R/fit.R
R/fit_helpers.R
R/misc.R
R/predict_class.R
man/fit.Rd
tests/testthat/test-predict_formats.R

Currently, we accidentally strip off the `ordered` element of factors when we make class predictions. 
Relevant to #953

predict ordinal factors from ordinal regression models

---

R/aaa_models.R
tests/testthat/_snaps/re_registration.md

Closes #1201. Don't love the `paste0()` smell but seems the substitution of a string that _also_ contains a substitution is a no-go.

correct formatting in model registration error

---

NEWS.md
R/tunable.R
parsnip.Rproj
tests/testthat/test-tunable.R

Add mixture to brulee's tunable

---

R/mlp.R
tests/testthat/test-mlp_keras.R

i was a little too fast in https://github.com/tidymodels/parsnip/pull/1244, this PR fixes the mistake and adds a test

fix abort call and add test for wrong activation

---

.Rbuildignore
DESCRIPTION
vignettes/articles/.gitignore
vignettes/articles/checklists.Rmd

Moving the checklists here for better visibility, instead of https://github.com/tidymodels/tidymodels/pull/97

Add dev checklists for new models/engines/engine docs

---

R/mlp.R
R/tunable.R
tests/testthat/_snaps/mlp_keras.md
tests/testthat/test-tunable.R

```r
model <- 
mlp(activation = tune()) %>%
set_engine("keras") %>%
set_mode("classification")
set.seed(1)
res <- tune_grid(
workflow(class ~ ., model),
vfold_cv(sim_classification(1000), v = 2),
grid = 10
)
res |>
collect_metrics() |>
count(activation)
#> # A tibble: 10 × 2
#>    activation       n
#>    <chr>        <int>
#>  1 elu              3
#>  2 exponential      3
#>  3 hard_sigmoid     3
#>  4 linear           3
#>  5 selu             3
#>  6 sigmoid          3
#>  7 softmax          3
#>  8 softplus         3
#>  9 swish            3
#> 10 tanh             3
model <- 
mlp(activation = tune()) %>%
set_engine("brulee") %>%
set_mode("classification")
set.seed(1)
res <- tune_grid(
workflow(class ~ ., model),
vfold_cv(sim_classification(1000), v = 2),
grid = 10
) …
```

toggle mlp activation by engine

---

.github/workflows/R-CMD-check.yaml
NEWS.md
R/tidy_glmnet.R
tests/testthat/_snaps/mlp_keras.md

Closes #1261 
Tests forthcoming to extratests

Fix glmnet penalty check

---

R/svm_linear_data.R
tests/testthat/_snaps/translate.md

Related to tidymodels/tune#1039
Linear SVMs _have no kernel parameters_ but loudly complain that none were specified. Adding `kpar = list()` appears to shush it.
``` r
library(modeldata)
#> 
#> Attaching package: 'modeldata'
#> The following object is masked from 'package:datasets':
#> 
#>     penguins
res <- 
svm_linear(mode = "classification", engine = "kernlab") |> 
fit(Class ~ ., data = two_class_dat)
#>  Setting default kernel parameters
```
<sup>Created on 2025-07-15 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
``` r
library(modeldata)
#> 
#> Attaching package: 'modeldata'
#> The following object is masked from 'package:datasets':
#> 
#>     penguins
res <- 
svm_linear(mode = "classification", engine = "kernlab") |> 
fit(Class ~ ., data …
```

Quiet linear svm models

---

NEWS.md
R/tunable.R
man/details_boost_tree_lightgbm.Rd

`brulee_mlp_args` had switched the dials info for `stop_iter()` and `class_weights()`.

Error in parsnip tunable information for brulee

---

R/augment.R

Fixes #1212  and Air styled code

Fixes #1212 enabled augment() for quartile regression
